/* Modium – tệp xử lý ngôn ngữ.
   - Nội dung gốc của trang là tiếng Việt (vi). Mỗi mục trong EN là "câu tiếng Việt" -> "bản tiếng Anh".
   - Ngôn ngữ chưa có bản dịch sẽ hiển thị bằng tiếng Anh (đúng như cảnh báo trong phần Cài đặt).
   - Muốn thêm ngôn ngữ mới: tạo thêm một bảng như EN rồi đăng ký vào DICT bên dưới. */
(function () {
  var EN = {
    /* Thanh điều hướng */
    'Khám phá nội dung': 'Discover content', 'Công trình': 'Structures', 'Tài Liệu API': 'API Docs',
    'Tạo Map Đám Mây': 'Create Cloud Map', 'Tạo máy chủ': 'Create a server', 'Tải App': 'Get the app',
    'Đăng nhập': 'Log in', 'Cài đặt': 'Settings',
    /* Trang chủ */
    'Nơi dành cho': 'The place for', 'mod': 'mods', 'gói tài nguyên': 'resource packs', 'gói dữ liệu': 'data packs',
    'shader': 'shaders', 'modpack': 'modpacks', 'plugin': 'plugins', 'máy chủ': 'servers',
    'Khám phá, chơi và chia sẻ nội dung MiniWorld trên nền tảng được xây dựng cho cộng đồng.': 'Discover, play and share MiniWorld content on a platform built for the community.',
    'Khám phá các tài nguyên': 'Explore resources', 'Đăng ký': 'Sign up', 'Dự án nổi bật': 'Featured projects',
    'Ánh sáng 3D cho các khối phát sáng': '3D lighting for glowing blocks',
    'Hệ thống kho đồ theo tủ hồ sơ': 'Filing-cabinet style storage system',
    'Rừng sâu với sinh vật mới': 'Deep forest with new creatures',
    'Shader bầu trời chân thực': 'Realistic sky shader',
    'Logo Modium': 'Modium logo',
    /* Cài đặt */
    'HIỂN THỊ': 'DISPLAY', 'Giao diện': 'Appearance', 'Ngôn ngữ': 'Language',
    'Chọn chủ đề màu ưa thích của bạn.': 'Choose your preferred color theme.',
    'Đồng bộ với hệ thống': 'Sync with system', 'Sáng': 'Light', 'Tối': 'Dark',
    'Đồng bộ chủ đề trên các thiết bị': 'Sync theme across devices',
    'Dùng chủ đề này ở mọi nơi bạn đăng nhập. Tắt để giữ chủ đề riêng trên thiết bị này.': 'Use this theme everywhere you are signed in. Turn off to keep a separate theme on this device.',
    'Đồng bộ chủ đề': 'Sync theme',
    'Bố cục danh sách dự án': 'Project list layout',
    'Chọn bố cục cho từng trang hiển thị danh sách dự án.': 'Choose a layout for each page that shows a project list.',
    'Trang Mods': 'Mods page', 'Trang Plugin': 'Plugins page', 'Trang Gói dữ liệu': 'Data packs page',
    'Trang Shader': 'Shaders page', 'Trang Gói tài nguyên': 'Resource packs page', 'Trang Modpack': 'Modpacks page',
    'Hàng': 'Rows', 'Lưới': 'Grid',
    'Đổi ngôn ngữ có thể khiến một số nội dung hiển thị bằng tiếng Anh nếu chưa có bản dịch.': 'Changing the language may cause some content to appear in English if it has not been translated yet.',
    'Chọn ngôn ngữ ưa thích cho trang web.': 'Choose your preferred language for the website.',
    'Tìm ngôn ngữ...': 'Search languages...', 'Tìm ngôn ngữ': 'Search languages',
    'Ngôn ngữ tiêu chuẩn': 'Standard languages',
    /* Đăng nhập / đăng ký */
    'Đăng nhập vào Modium': 'Sign in to Modium', 'Email hoặc tên đăng nhập': 'Email or username', 'Email hoặc tên @': 'Email or @handle', 'Mật khẩu': 'Password',
    'Tiếp tục với Email': 'Continue with Email', 'Chưa có tài khoản?': 'Don\'t have an account?',
    'Đã có tài khoản?': 'Already have an account?', 'Tạo tài khoản Modium': 'Create a Modium account',
    'Tên đăng nhập': 'Username', 'Tên hiển thị': 'Display name', 'Tên @ (duy nhất)': 'Unique @handle', 'Tên @': '@handle', 'Xác nhận mật khẩu': 'Confirm password', 'Ít nhất 8 ký tự': 'At least 8 characters', 'Ít nhất 12 ký tự': 'At least 12 characters',
    'Tên này có thể trùng với người khác.': 'This name may be shared by other users.', 'Ví dụ: @minh_nguyen — chỉ gồm chữ, số, dấu _ và -.': 'Example: @minh_nguyen — letters, numbers, _ and - only.',
    'Chỉ gồm chữ, số, dấu _ và -': 'Letters, numbers, _ and - only',
    'Giữ cho tôi cập nhật những điều thú vị Modium đang làm qua email': 'Keep me updated on the cool things Modium is working on via email',
    'Hoàn tất đăng ký': 'Complete sign up',
    'Vui lòng nhập đầy đủ thông tin.': 'Please fill in all fields.',
    'Email/tên đăng nhập hoặc mật khẩu không đúng.': 'Incorrect email/username or password.',
    'Tên đăng nhập phải dài 3–20 ký tự, chỉ gồm chữ, số, dấu _ và -.': 'Username must be 3–20 characters and contain only letters, numbers, _ and -.', 'Tên @ phải dài 3–20 ký tự, chỉ gồm chữ, số, dấu _ và -.': '@handle must be 3–20 characters and contain only letters, numbers, _ and -.', 'Tên @ đã được sử dụng.': 'That @handle is already taken.',
    'Email không hợp lệ.': 'Invalid email address.',
    'Mật khẩu phải có ít nhất 8 ký tự.': 'Password must be at least 8 characters.', 'Mật khẩu phải có 12–128 ký tự và không chứa ký tự điều khiển.': 'Password must be 12–128 characters and contain no control characters.', 'Tên hiển thị dài 1–40 ký tự và không chứa ký tự đặc biệt nguy hiểm.': 'Display name must be 1–40 characters and contain no unsafe characters.',
    'Mật khẩu xác nhận không khớp.': 'Passwords do not match.',
    'Tên đăng nhập đã được sử dụng.': 'That username is already taken.',
    'Email đã được sử dụng.': 'That email is already in use.',
    'Trình duyệt này không hỗ trợ mã hóa mật khẩu an toàn.': 'This browser does not support secure password hashing.',
    'Không thể lưu tài khoản. Hãy kiểm tra trình duyệt có đang chặn lưu trữ không.': 'Could not save the account. Check whether your browser is blocking storage.',
    'Bạn đã thử quá nhiều lần. Hãy thử lại sau 30 giây.': 'Too many attempts. Please try again in 30 seconds.',
    'Đăng nhập bằng dịch vụ bên ngoài cần máy chủ nên chưa khả dụng trong bản demo này.': 'Signing in with an external service needs a server, so it is not available in this demo yet.',
    'Khôi phục mật khẩu cần máy chủ gửi email nên chưa khả dụng trong bản demo này.': 'Password recovery needs a server to send email, so it is not available in this demo yet.',
    'Tiếp tục với passkey': 'Continue with passkey', 'Quên mật khẩu': 'Forgot password',
    /* Menu tài khoản */
    'Menu tài khoản': 'Account menu', 'Đăng bài': 'Publish', 'Hồ sơ': 'Profile', 'Nâng cấp lên Modium+': 'Upgrade to Modium+',
    'Máy chủ của tôi': 'My servers', 'Thông báo': 'Notifications', 'Báo cáo đang xử lý': 'Active reports',
    'Bộ sưu tập': 'Collections', 'Dự án': 'Projects', 'Tổ chức': 'Organizations', 'Phân tích': 'Analytics',
    'Doanh thu': 'Revenue', 'Chuyển tài khoản': 'Switch account', 'Đăng xuất': 'Sign out',
    /* Trang chủ sau khi đăng nhập, hồ sơ, bảng điều khiển */
    'Chào mừng trở lại,': 'Welcome back,', 'Đến bảng điều khiển': 'Go to dashboard', 'Truy cập nhanh': 'Quick access',
    'Xem thông tin tài khoản của bạn': 'View your account details', 'Theo dõi hoạt động của bạn': 'Track your activity',
    'Tùy chỉnh giao diện và ngôn ngữ': 'Customize appearance and language',
    'Bảng điều khiển': 'Dashboard', 'Tham gia': 'Joined', 'Lượt tải': 'Downloads', 'Người theo dõi': 'Followers',
    'Bạn chưa có dự án nào': 'You have no projects yet',
    'Tính năng đăng dự án chưa khả dụng trong bản demo này.': 'Publishing projects is not available in this demo yet.',
    /* Trang duyệt tài nguyên */
    'Mods': 'Mods', 'Gói tài nguyên': 'Resource Packs', 'Gói dữ liệu': 'Data Packs', 'Shader': 'Shaders', 'Modpack': 'Modpacks', 'Plugin': 'Plugins', 'Máy chủ': 'Servers',
    'Loại tài nguyên': 'Resource type', 'Bộ lọc': 'Filters',
    'Tìm kiếm dự án...': 'Search projects...', 'Tìm kiếm dự án': 'Search projects',
    'Phiên bản trò chơi': 'Game version', 'Tìm kiếm...': 'Search...', 'Tìm phiên bản': 'Search versions', 'Hiện tất cả phiên bản': 'Show all versions',
    'Bộ nạp': 'Loader', 'Hiện thêm': 'Show more', 'Thu gọn': 'Show less', 'Danh mục': 'Category', 'Môi trường': 'Environment',
    'Phía máy khách': 'Client-side', 'Phía máy chủ': 'Server-side', 'Máy khách và máy chủ': 'Client and server', 'Máy khách hoặc máy chủ': 'Client or server',
    'Giấy phép': 'License', 'Mã nguồn mở': 'Open source', 'Phụ thuộc vào': 'Depends on', 'Tìm một dự án...': 'Search for a project...', 'Tìm dự án phụ thuộc': 'Search dependency project',
    'Loại trừ nâng cao': 'Advanced exclusions', 'Ẩn các danh mục sau': 'Hide these categories',
    'Sắp xếp theo:': 'Sort by:', 'Mức liên quan': 'Relevance', 'Lượt tải nhiều nhất': 'Most downloads', 'Được theo dõi nhiều nhất': 'Most followed', 'Cập nhật gần đây': 'Recently updated',
    'Hiển thị:': 'View:', 'Đổi bố cục': 'Change layout', 'Trang trước': 'Previous page', 'Trang sau': 'Next page', 'kết quả': 'results', 'bởi': 'by',
    'Không tìm thấy dự án phù hợp': 'No matching projects found', 'Hãy thử bỏ bớt bộ lọc.': 'Try removing some filters.', 'Xóa bộ lọc': 'Clear filters',
    'Dữ liệu minh họa: các dự án trên trang này là mẫu tự tạo.': 'Demo data: the projects on this page are made-up samples.',
    'Phiêu lưu': 'Adventure', 'Bị nguyền': 'Cursed', 'Trang trí': 'Decoration', 'Kinh tế': 'Economy', 'Trang bị': 'Equipment', 'Thức ăn': 'Food',
    'Cơ chế game': 'Game mechanics', 'Thư viện': 'Library', 'Phép thuật': 'Magic', 'Quản lý': 'Management', 'Sinh vật': 'Mobs', 'Tối ưu hóa': 'Optimization',
    'Xã hội': 'Social', 'Kho chứa': 'Storage', 'Công nghệ': 'Technology', 'Vận chuyển': 'Transportation', 'Tiện ích': 'Utility', 'Tạo thế giới': 'World generation',
    'Độ phân giải': 'Resolution', '8x trở xuống': '8x or lower', '512x trở lên': '512x or higher',
    'Âm thanh': 'Audio', 'Khối': 'Blocks', 'Chiến đấu': 'Combat', 'Phông chữ': 'Fonts', 'Giao diện (GUI)': 'GUI', 'Vật phẩm': 'Items', 'Bản địa hóa': 'Locale', 'Mô hình': 'Models',
    'Loại trừ': 'Exclude',
    'Chưa có tài nguyên nào': 'No resources yet', 'Hãy là người đầu tiên chia sẻ sáng tạo của bạn với cộng đồng.': 'Be the first to share your creation with the community.', 'Đăng tài nguyên': 'Publish a resource',
    /* Thanh xác nhận thay đổi */
    'Bạn có những thay đổi chưa được lưu': 'You have unsaved changes', 'Đặt lại': 'Reset', 'Lưu': 'Save',
    /* Chân trang */
    'Modium là': 'Modium is', 'mã nguồn mở được làm bởi Vazkii': 'open source, made by Vazkii',
    'Giới thiệu': 'About', 'Tin tức': 'News', 'Nhật ký thay đổi': 'Changelog', 'Trạng thái': 'Status',
    'Tuyển dụng': 'Careers', 'Chương trình phần thưởng': 'Rewards program',
    'Sản phẩm': 'Products', 'Ứng dụng Modium': 'Modium app',
    'Tài nguyên': 'Resources', 'Trung tâm trợ giúp': 'Help center', 'Dịch thuật': 'Translations',
    'Báo cáo sự cố': 'Report an issue', 'Tài liệu API': 'API docs',
    'Pháp lý': 'Legal', 'Quy tắc về nội dung': 'Content rules', 'Điều khoản sử dụng': 'Terms of use',
    'Chính sách quyền riêng tư': 'Privacy policy', 'Thông báo bảo mật': 'Security notice',
    'Chính sách bản quyền và DMCA': 'Copyright and DMCA policy',
    'ĐÂY KHÔNG PHẢI WEB CHÍNH THỨ CỦA NHÀ PHÁT TRIỂN MINI WAN, ĐÂY LÀ MỘT DỰ ÁN TÔI MUỐN CÔNG KHAI MỘT SỐ THỨ VỚI MỌI NGƯỜI VÀ CHẮC CHẮN LÀ NÓ LEGIT': 'THIS IS NOT THE OFFICIAL WEBSITE OF THE MINI WAN DEVELOPERS. IT IS A PROJECT I WANT TO SHARE PUBLICLY WITH EVERYONE, AND IT IS DEFINITELY LEGIT',
    "Ai cũng thấy và tìm được dự án.": "Everyone can see and find the project.",
    "Bạn chưa có dự án nào!": "You don't have any projects yet!",
    "Bạn chưa đăng nhập.": "You are not logged in yet.",
    "Bạn đã vượt giới hạn tổng 100 MB tệp trong bản demo.": "You have exceeded the 100 MB total file limit in the demo.",
    "Chi tiết": "Details",
    "Chưa chọn tệp": "File not selected",
    "Chưa có gì để hiển thị ở đây.": "There's nothing to show here yet.",
    "Chưa có phiên bản nào được đăng.": "No versions have been posted yet.",
    "Chưa có thay đổi nào.": "There are no changes yet.",
    "Chưa có ảnh nào trong thư viện.": "There are no photos in the gallery yet.",
    "Chế độ hiển thị": "Display mode",
    "Chỉ bạn và cộng tác viên xem được.": "Only you and your collaborators can see it.",
    "Chỉ người có liên kết mới xem được.": "Only people with the link can see it.",
    "Chủ sở hữu": "Owner",
    "Chủ đề (chọn nhiều)": "Topics (select multiple)",
    "Có lỗi xảy ra, trình duyệt có thể không hỗ trợ mã hóa an toàn.": "An error occurred, the browser may not support secure encryption.",
    "Công khai": "Public",
    "Cập nhật": "Updated",
    "Cộng tác viên": "Collaborator",
    "Cộng tác viên (không bắt buộc)": "Collaborator (not required)",
    "Dùng URL": "Use URLs",
    "Dữ liệu thay đổi không hợp lệ.": "Changed data is invalid.",
    "Dự án không tồn tại hoặc bạn không có quyền truy cập.": "The project doesn't exist or you don't have access.",
    "Dự án này chưa có tệp hoặc đường dẫn tải xuống hợp lệ.": "This project does not have a valid file or download link yet.",
    "Email mới": "New email",
    "Español (España)": "Español (España)",
    "Español (Latinoamérica)": "Español (Latinoamérica)",
    "Français": "Français",
    "Giới thiệu chỉ được dài tối đa 160 ký tự.": "Introductions can only be up to 160 characters long.",
    "Hành động này không thể hoàn tác.": "This action cannot be undone.",
    "Hãy chia sẻ mod, modpack hay gói tài nguyên đầu tiên của bạn.": "Please share your first mod, modpack or resource pack.",
    "Hãy chọn chế độ hiển thị.": "Please select display mode.",
    "Hãy chọn loại dự án.": "Please select the project type.",
    "Hãy chọn tải tệp lên hoặc nhập URL tải xuống.": "Choose to upload a file or enter a download URL.",
    "Hãy chọn tệp cần tải lên.": "Select the file to upload.",
    "Hãy chọn độ phân giải của gói tài nguyên.": "Please select the resource pack resolution.",
    "Hãy nhập URL HTTP/HTTPS hợp lệ (không dùng javascript:, data: hoặc thông tin đăng nhập trong URL).": "Please enter a valid HTTP/HTTPS URL (don't use javascript:, data: or login information in the URL).",
    "Hãy nhập mô tả ngắn hợp lệ (tối đa 200 ký tự).": "Please enter a valid short description (maximum 200 characters).",
    "Hãy nhập đúng tên @ để xác nhận.": "Please enter the correct @ name to confirm.",
    "Hôm nay": "Today",
    "hôm nay": "today",
    "Kho tệp đang được mở ở thẻ khác. Hãy tải lại trang rồi thử lại.": "The file store is open in another tab. Please reload the page and try again.",
    "Không công khai": "Not public",
    "Không dọn được tệp.": "Unable to clean file.",
    "Không mở được kho tệp.": "Unable to open file store.",
    "Không thể cập nhật bảo mật tài khoản.": "Unable to update account security.",
    "Không thể lưu phiên đăng nhập. Hãy kiểm tra trình duyệt có đang chặn lưu trữ không.": "Unable to save login session. Check if your browser is blocking storage.",
    "Không thể lưu thay đổi.": "Unable to save changes.",
    "Không thể lưu tệp trong trình duyệt.": "The file cannot be saved in the browser.",
    "Không thể lưu tệp. Hãy kiểm tra dung lượng trống của trình duyệt.": "File could not be saved. Check your browser's free space.",
    "Không thể tạo dự án. Hãy thử lại.": "Unable to create project. Please try again.",
    "Không thể tạo khóa 2FA trên trình duyệt này.": "2FA keys cannot be generated on this browser.",
    "Không thể tải tệp. Hãy thử lại.": "Could not load file. Please try again.",
    "Không thể xóa dữ liệu dự án của tài khoản.": "The account's project data cannot be deleted.",
    "Không thể xóa tài khoản.": "Account cannot be deleted.",
    "Không thể đọc tệp trong trình duyệt. Hãy thử lại.": "The file cannot be read in the browser. Please try again.",
    "Không tìm thấy tệp trên thiết bị này. Trong bản demo, tệp upload chưa được đồng bộ lên máy chủ.": "Files not found on this device. In the demo, the uploaded file has not been synchronized to the server.",
    "Không xóa được tệp tạm.": "Unable to delete temporary files.",
    "Không đọc được tệp.": "Unable to read file.",
    "Loại dự án": "Project type",
    "Magyar (Magyarország)": "Magyar (Magyarorszag)",
    "Mã 6 số hiện trong ứng dụng": "The 6-digit code appears in the application",
    "Mã không đúng. Hãy thử mã mới trong ứng dụng.": "Code is incorrect. Try the new code in the app.",
    "Mã xác thực 2 bước": "2-step authentication code",
    "Mã xác thực không đúng.": "Authentication code is incorrect.",
    "Mô tả": "Describe",
    "Mô tả ngắn": "Short description",
    "Mật khẩu hiện tại": "Current password",
    "Mật khẩu hiện tại không đúng.": "Current password is incorrect.",
    "Mật khẩu mới (≥ 12 ký tự)": "New password (≥ 12 characters)",
    "Mật khẩu mới phải có 12–128 ký tự và không chứa ký tự điều khiển.": "The new password must be 12–128 characters long and contain no control characters.",
    "Người dùng Modium.": "Modium users.",
    "Người dùng này chưa có dự án nào!": "This user doesn't have any projects yet!",
    "Người sáng tạo": "Creator",
    "Nhập mã xác thực 2 bước từ ứng dụng của bạn.": "Enter the 2-step authentication code from your app.",
    "Phiên bản": "Version",
    "Riêng tư": "Private",
    "Thiết lập": "Establish",
    "Thông tin": "Information",
    "Nền tảng": "Platform",
    "Loại": "Type",
    "Hiển thị": "Visibility",
    "Tải xuống": "Download",
    "Thẻ": "Card",
    "Tiếng Việt": "Vietnamese",
    "Trình duyệt không hỗ trợ lưu tệp an toàn (IndexedDB).": "The browser does not support secure file saving (IndexedDB).",
    "Trình duyệt không hỗ trợ tạo mã tệp an toàn.": "The browser does not support secure file encryption.",
    "Tài khoản và bảo mật": "Account and security",
    "Tài khoản đã đạt giới hạn 100 dự án trong bản demo.": "The account has reached its limit of 100 projects in the demo.",
    "Tên @ không hợp lệ.": "@Name is invalid.",
    "Tên @ không thể đổi sau khi tạo tài khoản để bảo vệ liên kết dự án.": "@name cannot be changed after account creation to protect project links.",
    "Tên dự án": "Project name",
    "Tên dự án phải dài 3–40 ký tự hợp lệ.": "The project name must be 3–40 valid characters long.",
    "Tên tệp không hợp lệ.": "Invalid file name.",
    "Tạo dự án": "Create project",
    "Tải tệp lên": "Upload files",
    "Tải về bản sao dữ liệu tài khoản của bạn (JSON).": "Download a copy of your account data (JSON).",
    "Tất cả": "All",
    "Tắt 2FA": "Turn off 2FA",
    "Tệp không phải ảnh hợp lệ.": "The file is not a valid image.",
    "Tệp phải có dung lượng từ 1 byte đến 25 MB.": "Files must be between 1 byte and 25 MB.",
    "Tệp phải từ 1 byte đến 25 MB.": "Files must be between 1 byte and 25 MB.",
    "Tệp tải xuống": "Download file",
    "Tệp vượt quá giới hạn dung lượng.": "File exceeds capacity limit.",
    "URL chỉ gồm chữ thường, số, dấu - (3–40 ký tự).": "URLs contain only lowercase letters, numbers, and - signs (3–40 characters).",
    "URL này đã được dùng, hãy đổi tên khác.": "This URL is already in use, please change the name.",
    "Xuất": "Export",
    "Xuất dữ liệu": "Export data",
    "Xác nhận mật khẩu mới": "Confirm new password",
    "Xác thực hai bước (2FA)": "Two-step authentication (2FA)",
    "Xóa": "Erase",
    "Xóa tài khoản": "Delete account",
    "lượt tải": "downloads",
    "ngày trước": "days ago",
    "người theo dõi": "followers",
    "năm trước": "last year",
    "tháng trước": "last month",
    "Đang chuẩn bị tải xuống…": "Preparing to download…",
    "Đang tạo…": "Creating…",
    "Đã bật xác thực hai bước.": "Two-step authentication enabled.",
    "Đã bắt đầu tải xuống.": "Download has started.",
    "Đã lưu thay đổi.": "Changes saved.",
    "Đã lưu.": "Saved.",
    "Đã tắt xác thực hai bước.": "Two-step authentication disabled.",
    "Đã đổi email.": "Email changed.",
    "Đã đổi mật khẩu.": "Password changed.",
    "Đăng": "Published",
    "Đổi email": "Change email",
    "Đổi mật khẩu": "Change password",
    "Đổi mật khẩu đăng nhập của bạn.": "Change your login password.",
    "Độ phân giải gói tài nguyên": "Resource pack resolution",
    "Ảnh đại diện không hợp lệ.": "Invalid profile picture.",
    "Đang kết nối đến Modium…": "Connecting to Modium…",
    "Không thể kết nối đến dịch vụ Modium.": "Could not connect to Modium services.",
    "Hãy kiểm tra cấu hình Supabase và thử lại.": "Check the Supabase configuration and try again.",
    "Thử lại": "Retry",
    "Nếu email tồn tại, liên kết đặt lại mật khẩu sẽ được gửi đến hộp thư.": "If the email exists, a password-reset link will be sent to its inbox.",
    "Kiểm tra email để xác nhận tài khoản trước khi đăng nhập.": "Check your email to confirm your account before signing in.",
    "Không thể lưu thay đổi. Hãy thử lại.": "Could not save changes. Please try again.",
    "Không thể tạo khóa xác thực hai bước.": "Could not create a two-factor authentication key.",
    "Tệp tải lên tối đa 25 MB và được lưu trong kho riêng của Modium.": "Uploads are limited to 25 MB and stored in Modium's private storage.",
    "Hãy xác minh mật khẩu và mã 2FA hiện tại.": "Verify your current password and 2FA code.",
    "Không thể tải file lên máy chủ. Kiểm tra quota/dung lượng rồi thử lại.": "Could not upload the file. Check your storage quota and try again.",
    "Tài khoản đã đạt giới hạn 100 dự án.": "This account has reached the 100-project limit.",
    "Nhập mã từ ứng dụng xác thực, rồi đăng nhập lại.": "Enter the code from your authenticator app, then sign in again.",
    "Đặt lại mật khẩu": "Reset password",
    "Nhập mật khẩu mới để hoàn tất khôi phục.": "Enter a new password to finish recovery.",
    "Liên kết khôi phục không hợp lệ hoặc đã hết hạn.": "This recovery link is invalid or has expired.",
    "Không thể cập nhật mật khẩu. Hãy thử lại.": "Could not update the password. Please try again.",
    "Lưu mật khẩu mới": "Save new password",
    "Mật khẩu đã được cập nhật.": "Your password has been updated.",
    "Mã 2FA hiện tại": "Current 2FA code",
    "Hãy nhập mã 2FA hiện tại.": "Enter your current 2FA code.",
    "Không thể xác minh trạng thái xác thực của tài khoản.": "Could not verify the account's authentication status.",
    "Không thể gửi email khôi phục.": "Could not send the recovery email."
  };

  /* Đăng ký ngôn ngữ: mã -> bảng dịch. 'vi' là bản gốc nên không cần bảng. */
  
  var ES_419 = {
    "Khám phá nội dung": "Descubre contenido",
    "Công trình": "Estructuras",
    "Tài Liệu API": "Documentos API",
    "Tạo Map Đám Mây": "Crear mapa de la nube",
    "Tạo máy chủ": "crear un servidor",
    "Tải App": "Obtén la aplicación",
    "Đăng nhập": "Acceso",
    "Cài đặt": "Ajustes",
    "Nơi dành cho": "El lugar para",
    "mod": "mods",
    "gói tài nguyên": "paquetes de recursos",
    "gói dữ liệu": "paquetes de datos",
    "shader": "shaders",
    "modpack": "modpacks",
    "plugin": "plugins",
    "máy chủ": "servidores",
    "Khám phá, chơi và chia sẻ nội dung MiniWorld trên nền tảng được xây dựng cho cộng đồng.": "Descubra, juegue y comparta contenido de MiniWorld en una plataforma creada para la comunidad.",
    "Khám phá các tài nguyên": "Explorar recursos",
    "Đăng ký": "Inscribirse",
    "Dự án nổi bật": "Proyectos destacados",
    "Ánh sáng 3D cho các khối phát sáng": "Iluminación 3D para bloques brillantes",
    "Hệ thống kho đồ theo tủ hồ sơ": "Sistema de almacenamiento estilo archivador",
    "Rừng sâu với sinh vật mới": "Bosque profundo con nuevas criaturas.",
    "Shader bầu trời chân thực": "Sombreador de cielo realista",
    "Logo Modium": "Logo de Modium",
    "HIỂN THỊ": "MOSTRAR",
    "Giao diện": "Apariencia",
    "Ngôn ngữ": "Idioma",
    "Chọn chủ đề màu ưa thích của bạn.": "Elija su tema de color preferido.",
    "Đồng bộ với hệ thống": "Sincronizar con el sistema",
    "Sáng": "Luz",
    "Tối": "Oscuro",
    "Đồng bộ chủ đề trên các thiết bị": "Sincronizar tema entre dispositivos",
    "Dùng chủ đề này ở mọi nơi bạn đăng nhập. Tắt để giữ chủ đề riêng trên thiết bị này.": "Utilice este tema en todos los lugares donde haya iniciado sesión. Desactívelo para mantener un tema separado en este dispositivo.",
    "Đồng bộ chủ đề": "Tema de sincronización",
    "Bố cục danh sách dự án": "Diseño de lista de proyectos",
    "Chọn bố cục cho từng trang hiển thị danh sách dự án.": "Elija un diseño para cada página que muestre una lista de proyectos.",
    "Trang Mods": "Página de modificaciones",
    "Trang Plugin": "Página de complementos",
    "Trang Gói dữ liệu": "Página de paquetes de datos",
    "Trang Shader": "Página de sombreadores",
    "Trang Gói tài nguyên": "Página de paquetes de recursos",
    "Trang Modpack": "Página de paquetes de modificaciones",
    "Hàng": "Filas",
    "Lưới": "Red",
    "Đổi ngôn ngữ có thể khiến một số nội dung hiển thị bằng tiếng Anh nếu chưa có bản dịch.": "Cambiar el idioma puede hacer que algún contenido aparezca en inglés si aún no ha sido traducido.",
    "Chọn ngôn ngữ ưa thích cho trang web.": "Elija su idioma preferido para el sitio web.",
    "Tìm ngôn ngữ...": "Buscar idiomas...",
    "Tìm ngôn ngữ": "Idiomas de búsqueda",
    "Ngôn ngữ tiêu chuẩn": "Idiomas estándar",
    "Đăng nhập vào Modium": "Iniciar sesión en Modium",
    "Email hoặc tên đăng nhập": "Correo electrónico o nombre de usuario",
    "Email hoặc tên @": "Correo electrónico o @handle",
    "Mật khẩu": "Contraseña",
    "Tiếp tục với Email": "Continuar con el correo electrónico",
    "Chưa có tài khoản?": "¿No tienes una cuenta?",
    "Đã có tài khoản?": "¿Ya tienes una cuenta?",
    "Tạo tài khoản Modium": "Crea una cuenta en Modium",
    "Tên đăng nhập": "Nombre de usuario",
    "Tên hiển thị": "Nombre para mostrar",
    "Tên @ (duy nhất)": "@handle único",
    "Tên @": "@manejar",
    "Xác nhận mật khẩu": "Confirmar Contraseña",
    "Ít nhất 8 ký tự": "Al menos 8 caracteres",
    "Ít nhất 12 ký tự": "Al menos 12 caracteres",
    "Tên này có thể trùng với người khác.": "Este nombre puede ser compartido por otros usuarios.",
    "Ví dụ: @minh_nguyen — chỉ gồm chữ, số, dấu _ và -.": "Ejemplo: @minh_nguyen: letras, números, _ y - únicamente.",
    "Chỉ gồm chữ, số, dấu _ và -": "Letras, números, _ y - únicamente",
    "Giữ cho tôi cập nhật những điều thú vị Modium đang làm qua email": "Mantenme informado sobre las cosas interesantes en las que Modium está trabajando por correo electrónico.",
    "Hoàn tất đăng ký": "Regístrate completo",
    "Vui lòng nhập đầy đủ thông tin.": "Por favor complete todos los campos.",
    "Email/tên đăng nhập hoặc mật khẩu không đúng.": "Correo electrónico/nombre de usuario o contraseña incorrectos.",
    "Tên đăng nhập phải dài 3–20 ký tự, chỉ gồm chữ, số, dấu _ và -.": "El nombre de usuario debe tener entre 3 y 20 caracteres y contener solo letras, números, _ y -.",
    "Tên @ phải dài 3–20 ký tự, chỉ gồm chữ, số, dấu _ và -.": "@handle debe tener entre 3 y 20 caracteres y contener solo letras, números, _ y -.",
    "Tên @ đã được sử dụng.": "Ese @handle ya está en uso.",
    "Email không hợp lệ.": "Dirección de correo electrónico no válida.",
    "Mật khẩu phải có ít nhất 8 ký tự.": "La contraseña debe tener al menos 8 caracteres.",
    "Mật khẩu phải có 12–128 ký tự và không chứa ký tự điều khiển.": "La contraseña debe tener entre 12 y 128 caracteres y no contener caracteres de control.",
    "Tên hiển thị dài 1–40 ký tự và không chứa ký tự đặc biệt nguy hiểm.": "El nombre para mostrar debe tener entre 1 y 40 caracteres y no contener caracteres no seguros.",
    "Mật khẩu xác nhận không khớp.": "Las contraseñas no coinciden.",
    "Tên đăng nhập đã được sử dụng.": "Ese nombre de usuario ya está en uso.",
    "Email đã được sử dụng.": "Ese correo electrónico ya está en uso.",
    "Trình duyệt này không hỗ trợ mã hóa mật khẩu an toàn.": "Este navegador no admite el hash seguro de contraseñas.",
    "Không thể lưu tài khoản. Hãy kiểm tra trình duyệt có đang chặn lưu trữ không.": "No se pudo guardar la cuenta. Compruebe si su navegador está bloqueando el almacenamiento.",
    "Bạn đã thử quá nhiều lần. Hãy thử lại sau 30 giây.": "Demasiados intentos. Inténtelo de nuevo en 30 segundos.",
    "Đăng nhập bằng dịch vụ bên ngoài cần máy chủ nên chưa khả dụng trong bản demo này.": "Iniciar sesión con un servicio externo necesita un servidor, por lo que aún no está disponible en esta demostración.",
    "Khôi phục mật khẩu cần máy chủ gửi email nên chưa khả dụng trong bản demo này.": "La recuperación de contraseña necesita un servidor para enviar correo electrónico, por lo que aún no está disponible en esta demostración.",
    "Tiếp tục với passkey": "Continuar con la clave de acceso",
    "Quên mật khẩu": "Has olvidado tu contraseña",
    "Menu tài khoản": "Menú de cuenta",
    "Đăng bài": "Publicar",
    "Hồ sơ": "Perfil",
    "Nâng cấp lên Modium+": "Actualízate a Modo+",
    "Máy chủ của tôi": "Mis servidores",
    "Thông báo": "Notificaciones",
    "Báo cáo đang xử lý": "Informes activos",
    "Bộ sưu tập": "Colecciones",
    "Dự án": "Proyectos",
    "Tổ chức": "Organizaciones",
    "Phân tích": "Analítica",
    "Doanh thu": "Ganancia",
    "Chuyển tài khoản": "Cambiar de cuenta",
    "Đăng xuất": "desconectar",
    "Chào mừng trở lại,": "Bienvenido de nuevo,",
    "Đến bảng điều khiển": "Ir al panel",
    "Truy cập nhanh": "Acceso rápido",
    "Xem thông tin tài khoản của bạn": "Ver los detalles de su cuenta",
    "Theo dõi hoạt động của bạn": "Sigue tu actividad",
    "Tùy chỉnh giao diện và ngôn ngữ": "Personaliza la apariencia y el idioma.",
    "Bảng điều khiển": "Panel",
    "Tham gia": "Unido",
    "Lượt tải": "Descargas",
    "Người theo dõi": "Seguidores",
    "Bạn chưa có dự án nào": "Aún no tienes proyectos",
    "Tính năng đăng dự án chưa khả dụng trong bản demo này.": "La publicación de proyectos aún no está disponible en esta demostración.",
    "Mods": "Modificaciones",
    "Gói tài nguyên": "Paquetes de recursos",
    "Gói dữ liệu": "Paquetes de datos",
    "Shader": "Sombreadores",
    "Modpack": "Paquetes de modificaciones",
    "Plugin": "Complementos",
    "Máy chủ": "Servidores",
    "Loại tài nguyên": "Tipo de recurso",
    "Bộ lọc": "Filtros",
    "Tìm kiếm dự án...": "Buscar proyectos...",
    "Tìm kiếm dự án": "Buscar proyectos",
    "Phiên bản trò chơi": "Versión del juego",
    "Tìm kiếm...": "Buscar...",
    "Tìm phiên bản": "Buscar versiones",
    "Hiện tất cả phiên bản": "Mostrar todas las versiones",
    "Bộ nạp": "Cargador",
    "Hiện thêm": "Mostrar más",
    "Thu gọn": "Mostrar menos",
    "Danh mục": "Categoría",
    "Môi trường": "Ambiente",
    "Phía máy khách": "Lado del cliente",
    "Phía máy chủ": "Del lado del servidor",
    "Máy khách và máy chủ": "Cliente y servidor",
    "Máy khách hoặc máy chủ": "Cliente o servidor",
    "Giấy phép": "Licencia",
    "Mã nguồn mở": "Código abierto",
    "Phụ thuộc vào": "Depende de",
    "Tìm một dự án...": "Busca un proyecto...",
    "Tìm dự án phụ thuộc": "Proyecto de dependencia de búsqueda",
    "Loại trừ nâng cao": "Exclusiones avanzadas",
    "Ẩn các danh mục sau": "Ocultar estas categorías",
    "Sắp xếp theo:": "Ordenar por:",
    "Mức liên quan": "Pertinencia",
    "Lượt tải nhiều nhất": "La mayoría de las descargas",
    "Được theo dõi nhiều nhất": "Los más seguidos",
    "Cập nhật gần đây": "Actualizado recientemente",
    "Hiển thị:": "Vista:",
    "Đổi bố cục": "Cambiar diseño",
    "Trang trước": "Pagina anterior",
    "Trang sau": "Página siguiente",
    "kết quả": "resultados",
    "bởi": "por",
    "Không tìm thấy dự án phù hợp": "No se encontraron proyectos coincidentes",
    "Hãy thử bỏ bớt bộ lọc.": "Intente eliminar algunos filtros.",
    "Xóa bộ lọc": "Limpiar filtros",
    "Dữ liệu minh họa: các dự án trên trang này là mẫu tự tạo.": "Datos de demostración: los proyectos de esta página son muestras inventadas.",
    "Phiêu lưu": "Aventura",
    "Bị nguyền": "Maldito",
    "Trang trí": "Decoración",
    "Kinh tế": "Economía",
    "Trang bị": "Equipo",
    "Thức ăn": "Alimento",
    "Cơ chế game": "Mecánica de juego",
    "Thư viện": "Biblioteca",
    "Phép thuật": "Magia",
    "Quản lý": "Gestión",
    "Sinh vật": "turbas",
    "Tối ưu hóa": "Mejoramiento",
    "Xã hội": "Social",
    "Kho chứa": "Almacenamiento",
    "Công nghệ": "Tecnología",
    "Vận chuyển": "Transporte",
    "Tiện ích": "Utilidad",
    "Tạo thế giới": "generación mundial",
    "Độ phân giải": "Resolución",
    "8x trở xuống": "8x o menos",
    "512x trở lên": "512x o superior",
    "Âm thanh": "Audio",
    "Khối": "Bloques",
    "Chiến đấu": "Combatir",
    "Phông chữ": "Fuentes",
    "Giao diện (GUI)": "GUI",
    "Vật phẩm": "Elementos",
    "Bản địa hóa": "Lugar",
    "Mô hình": "Modelos",
    "Loại trừ": "Excluir",
    "Chưa có tài nguyên nào": "Aún no hay recursos",
    "Hãy là người đầu tiên chia sẻ sáng tạo của bạn với cộng đồng.": "Sé el primero en compartir tu creación con la comunidad.",
    "Đăng tài nguyên": "Publicar un recurso",
    "Bạn có những thay đổi chưa được lưu": "Tienes cambios sin guardar",
    "Đặt lại": "Reiniciar",
    "Lưu": "Ahorrar",
    "Modium là": "El modo es",
    "mã nguồn mở được làm bởi Vazkii": "código abierto, hecho por Vazkii",
    "Giới thiệu": "Acerca de",
    "Tin tức": "Noticias",
    "Nhật ký thay đổi": "Registro de cambios",
    "Trạng thái": "Estado",
    "Tuyển dụng": "Carreras",
    "Chương trình phần thưởng": "Programa de recompensas",
    "Sản phẩm": "Productos",
    "Ứng dụng Modium": "Aplicación moderada",
    "Tài nguyên": "Recursos",
    "Trung tâm trợ giúp": "Centro de ayuda",
    "Dịch thuật": "Traducciones",
    "Báo cáo sự cố": "Informar un problema",
    "Tài liệu API": "Documentos API",
    "Pháp lý": "Legal",
    "Quy tắc về nội dung": "Reglas de contenido",
    "Điều khoản sử dụng": "Condiciones de uso",
    "Chính sách quyền riêng tư": "Política de privacidad",
    "Thông báo bảo mật": "Aviso de seguridad",
    "Chính sách bản quyền và DMCA": "Política de derechos de autor y DMCA",
    "ĐÂY KHÔNG PHẢI WEB CHÍNH THỨ CỦA NHÀ PHÁT TRIỂN MINI WAN, ĐÂY LÀ MỘT DỰ ÁN TÔI MUỐN CÔNG KHAI MỘT SỐ THỨ VỚI MỌI NGƯỜI VÀ CHẮC CHẮN LÀ NÓ LEGIT": "ESTE NO ES EL SITIO WEB OFICIAL DE LOS DESARROLLADORES DE MINI WAN. ES UN PROYECTO QUE QUIERO COMPARTIR PÚBLICAMENTE CON TODOS, Y DEFINITIVAMENTE ES LEGÍTIMO",
    "Ai cũng thấy và tìm được dự án.": "Todos pueden ver y encontrar el proyecto.",
    "Bạn chưa có dự án nào!": "¡Aún no tienes ningún proyecto!",
    "Bạn chưa đăng nhập.": "Aún no has iniciado sesión.",
    "Bạn đã vượt giới hạn tổng 100 MB tệp trong bản demo.": "Ha excedido el límite total de archivos de 100 MB en la demostración.",
    "Chi tiết": "Detalles",
    "Chưa chọn tệp": "Archivo no seleccionado",
    "Chưa có gì để hiển thị ở đây.": "No hay nada que mostrar aquí todavía.",
    "Chưa có phiên bản nào được đăng.": "Aún no se han publicado versiones.",
    "Chưa có thay đổi nào.": "Aún no hay cambios.",
    "Chưa có ảnh nào trong thư viện.": "Aún no hay fotos en la galería.",
    "Chế độ hiển thị": "Modo de visualización",
    "Chỉ bạn và cộng tác viên xem được.": "Sólo tú y tus colaboradores podéis verlo.",
    "Chỉ người có liên kết mới xem được.": "Sólo las personas con el enlace podrán verlo.",
    "Chủ sở hữu": "Dueño",
    "Chủ đề (chọn nhiều)": "Temas (seleccione varios)",
    "Có lỗi xảy ra, trình duyệt có thể không hỗ trợ mã hóa an toàn.": "Se produjo un error; es posible que el navegador no admita el cifrado seguro.",
    "Công khai": "Público",
    "Cập nhật": "Actualizado",
    "Cộng tác viên": "Colaborador",
    "Cộng tác viên (không bắt buộc)": "Colaborador (no requerido)",
    "Dùng URL": "Usar URL",
    "Dữ liệu thay đổi không hợp lệ.": "Los datos modificados no son válidos.",
    "Dự án không tồn tại hoặc bạn không có quyền truy cập.": "El proyecto no existe o no tienes acceso.",
    "Dự án này chưa có tệp hoặc đường dẫn tải xuống hợp lệ.": "Este proyecto aún no tiene un archivo válido ni un enlace de descarga.",
    "Email mới": "Nuevo correo electrónico",
    "Español (España)": "Español (España)",
    "Español (Latinoamérica)": "Español (Latinoamérica)",
    "Français": "francés",
    "Giới thiệu chỉ được dài tối đa 160 ký tự.": "Las presentaciones solo pueden tener hasta 160 caracteres.",
    "Hành động này không thể hoàn tác.": "Esta acción no se puede deshacer.",
    "Hãy chia sẻ mod, modpack hay gói tài nguyên đầu tiên của bạn.": "Comparta su primer mod, modpack o paquete de recursos.",
    "Hãy chọn chế độ hiển thị.": "Seleccione el modo de visualización.",
    "Hãy chọn loại dự án.": "Por favor seleccione el tipo de proyecto.",
    "Hãy chọn tải tệp lên hoặc nhập URL tải xuống.": "Elija cargar un archivo o ingresar una URL de descarga.",
    "Hãy chọn tệp cần tải lên.": "Seleccione el archivo para cargar.",
    "Hãy chọn độ phân giải của gói tài nguyên.": "Seleccione la resolución del paquete de recursos.",
    "Hãy nhập URL HTTP/HTTPS hợp lệ (không dùng javascript:, data: hoặc thông tin đăng nhập trong URL).": "Ingrese una URL HTTP/HTTPS válida (no use javascript:, datos: ni información de inicio de sesión en la URL).",
    "Hãy nhập mô tả ngắn hợp lệ (tối đa 200 ký tự).": "Introduzca una descripción breve válida (máximo 200 caracteres).",
    "Hãy nhập đúng tên @ để xác nhận.": "Ingrese el @ nombre correcto para confirmar.",
    "Hôm nay": "Hoy",
    "hôm nay": "hoy",
    "Kho tệp đang được mở ở thẻ khác. Hãy tải lại trang rồi thử lại.": "El almacén de archivos está abierto en otra pestaña. Vuelva a cargar la página e inténtelo de nuevo.",
    "Không công khai": "No publico",
    "Không dọn được tệp.": "No se puede limpiar el archivo.",
    "Không mở được kho tệp.": "No se puede abrir el almacén de archivos.",
    "Không thể cập nhật bảo mật tài khoản.": "No se puede actualizar la seguridad de la cuenta.",
    "Không thể lưu phiên đăng nhập. Hãy kiểm tra trình duyệt có đang chặn lưu trữ không.": "No se puede guardar la sesión de inicio de sesión. Compruebe si su navegador está bloqueando el almacenamiento.",
    "Không thể lưu thay đổi.": "No se pueden guardar los cambios.",
    "Không thể lưu tệp trong trình duyệt.": "El archivo no se puede guardar en el navegador.",
    "Không thể lưu tệp. Hãy kiểm tra dung lượng trống của trình duyệt.": "No se pudo guardar el archivo. Comprueba el espacio libre de tu navegador.",
    "Không thể tạo dự án. Hãy thử lại.": "No se puede crear el proyecto. Por favor inténtalo de nuevo.",
    "Không thể tạo khóa 2FA trên trình duyệt này.": "Las claves 2FA no se pueden generar en este navegador.",
    "Không thể tải tệp. Hãy thử lại.": "No se pudo cargar el archivo. Por favor inténtalo de nuevo.",
    "Không thể xóa dữ liệu dự án của tài khoản.": "Los datos del proyecto de la cuenta no se pueden eliminar.",
    "Không thể xóa tài khoản.": "La cuenta no se puede eliminar.",
    "Không thể đọc tệp trong trình duyệt. Hãy thử lại.": "El archivo no se puede leer en el navegador. Por favor inténtalo de nuevo.",
    "Không tìm thấy tệp trên thiết bị này. Trong bản demo, tệp upload chưa được đồng bộ lên máy chủ.": "Archivos no encontrados en este dispositivo. En la demostración, el archivo cargado no se sincronizó con el servidor.",
    "Không xóa được tệp tạm.": "No se pueden eliminar archivos temporales.",
    "Không đọc được tệp.": "No se puede leer el archivo.",
    "Loại dự án": "Tipo de proyecto",
    "Magyar (Magyarország)": "magiar (Magyarorszag)",
    "Mã 6 số hiện trong ứng dụng": "El código de 6 dígitos aparece en la aplicación.",
    "Mã không đúng. Hãy thử mã mới trong ứng dụng.": "El código es incorrecto. Pruebe el nuevo código en la aplicación.",
    "Mã xác thực 2 bước": "código de autenticación de 2 pasos",
    "Mã xác thực không đúng.": "El código de autenticación es incorrecto.",
    "Mô tả": "Describir",
    "Mô tả ngắn": "Breve descripción",
    "Mật khẩu hiện tại": "Contraseña actual",
    "Mật khẩu hiện tại không đúng.": "La contraseña actual es incorrecta.",
    "Mật khẩu mới (≥ 12 ký tự)": "Nueva contraseña (≥ 12 caracteres)",
    "Mật khẩu mới phải có 12–128 ký tự và không chứa ký tự điều khiển.": "La nueva contraseña debe tener entre 12 y 128 caracteres y no contener caracteres de control.",
    "Người dùng Modium.": "Usuarios del modo.",
    "Người dùng này chưa có dự án nào!": "¡Este usuario aún no tiene ningún proyecto!",
    "Người sáng tạo": "Creador",
    "Nhập mã xác thực 2 bước từ ứng dụng của bạn.": "Ingrese el código de autenticación de 2 pasos desde su aplicación.",
    "Phiên bản": "Versión",
    "Riêng tư": "Privado",
    "Thiết lập": "Establecer",
    "Thông tin": "Información",
    "Nền tảng": "Plataforma",
    "Loại": "Tipo",
    "Hiển thị": "Visibilidad",
    "Tải xuống": "Descargar",
    "Thẻ": "Tarjeta",
    "Tiếng Việt": "vietnamita",
    "Trình duyệt không hỗ trợ lưu tệp an toàn (IndexedDB).": "El navegador no admite el guardado seguro de archivos (IndexedDB).",
    "Trình duyệt không hỗ trợ tạo mã tệp an toàn.": "El navegador no admite el cifrado seguro de archivos.",
    "Tài khoản và bảo mật": "Cuenta y seguridad",
    "Tài khoản đã đạt giới hạn 100 dự án trong bản demo.": "La cuenta ha alcanzado su límite de 100 proyectos en la demostración.",
    "Tên @ không hợp lệ.": "@Nombre no es válido.",
    "Tên @ không thể đổi sau khi tạo tài khoản để bảo vệ liên kết dự án.": "@name no se puede cambiar después de la creación de la cuenta para proteger los enlaces del proyecto.",
    "Tên dự án": "Nombre del proyecto",
    "Tên dự án phải dài 3–40 ký tự hợp lệ.": "El nombre del proyecto debe tener entre 3 y 40 caracteres válidos.",
    "Tên tệp không hợp lệ.": "Nombre de archivo no válido.",
    "Tạo dự án": "Crear proyecto",
    "Tải tệp lên": "Subir archivos",
    "Tải về bản sao dữ liệu tài khoản của bạn (JSON).": "Descargue una copia de los datos de su cuenta (JSON).",
    "Tất cả": "Todo",
    "Tắt 2FA": "Desactivar 2FA",
    "Tệp không phải ảnh hợp lệ.": "El archivo no es una imagen válida.",
    "Tệp phải có dung lượng từ 1 byte đến 25 MB.": "Los archivos deben tener entre 1 byte y 25 MB.",
    "Tệp phải từ 1 byte đến 25 MB.": "Los archivos deben tener entre 1 byte y 25 MB.",
    "Tệp tải xuống": "Descargar archivo",
    "Tệp vượt quá giới hạn dung lượng.": "El archivo excede el límite de capacidad.",
    "URL chỉ gồm chữ thường, số, dấu - (3–40 ký tự).": "Las URL contienen solo letras minúsculas, números y signos - (de 3 a 40 caracteres).",
    "URL này đã được dùng, hãy đổi tên khác.": "Esta URL ya está en uso, cambie el nombre.",
    "Xuất": "Exportar",
    "Xuất dữ liệu": "Exportar datos",
    "Xác nhận mật khẩu mới": "Confirmar nueva contraseña",
    "Xác thực hai bước (2FA)": "Autenticación de dos pasos (2FA)",
    "Xóa": "Borrar",
    "Xóa tài khoản": "Eliminar cuenta",
    "lượt tải": "descargas",
    "ngày trước": "hace dias",
    "người theo dõi": "seguidores",
    "năm trước": "el año pasado",
    "tháng trước": "mes pasado",
    "Đang chuẩn bị tải xuống…": "Preparándose para descargar…",
    "Đang tạo…": "Creando…",
    "Đã bật xác thực hai bước.": "Autenticación de dos pasos habilitada.",
    "Đã bắt đầu tải xuống.": "La descarga ha comenzado.",
    "Đã lưu thay đổi.": "Cambios guardados.",
    "Đã lưu.": "Guardado.",
    "Đã tắt xác thực hai bước.": "Autenticación en dos pasos deshabilitada.",
    "Đã đổi email.": "Correo electrónico cambiado.",
    "Đã đổi mật khẩu.": "Contraseña cambiada.",
    "Đăng": "Publicado",
    "Đổi email": "Cambiar correo electrónico",
    "Đổi mật khẩu": "Cambiar la contraseña",
    "Đổi mật khẩu đăng nhập của bạn.": "Cambie su contraseña de inicio de sesión.",
    "Độ phân giải gói tài nguyên": "Resolución del paquete de recursos",
    "Ảnh đại diện không hợp lệ.": "Imagen de perfil no válida.",
    "Đang kết nối đến Modium…": "Conectando con Modium…",
    "Không thể kết nối đến dịch vụ Modium.": "No se pudo conectar con los servicios de Modium.",
    "Hãy kiểm tra cấu hình Supabase và thử lại.": "Revisa la configuración de Supabase e inténtalo de nuevo.",
    "Thử lại": "Reintentar",
    "Nếu email tồn tại, liên kết đặt lại mật khẩu sẽ được gửi đến hộp thư.": "Si el correo existe, se enviará un enlace para restablecer la contraseña.",
    "Kiểm tra email để xác nhận tài khoản trước khi đăng nhập.": "Revisa tu correo para confirmar la cuenta antes de iniciar sesión.",
    "Không thể lưu thay đổi. Hãy thử lại.": "No se pudieron guardar los cambios. Inténtalo de nuevo.",
    "Không thể tạo khóa xác thực hai bước.": "No se pudo crear la clave de autenticación en dos pasos.",
    "Tệp tải lên tối đa 25 MB và được lưu trong kho riêng của Modium.": "Los archivos subidos tienen un límite de 25 MB y se guardan en el almacenamiento privado de Modium.",
    "Hãy xác minh mật khẩu và mã 2FA hiện tại.": "Verifica tu contraseña actual y el código 2FA.",
    "Không thể tải file lên máy chủ. Kiểm tra quota/dung lượng rồi thử lại.": "No se pudo subir el archivo. Revisa tu cuota de almacenamiento e inténtalo de nuevo.",
    "Tài khoản đã đạt giới hạn 100 dự án.": "Esta cuenta alcanzó el límite de 100 proyectos.",
    "Nhập mã từ ứng dụng xác thực, rồi đăng nhập lại.": "Ingresa el código de tu aplicación de autenticación y vuelve a iniciar sesión.",
    "Đặt lại mật khẩu": "Restablecer contraseña",
    "Nhập mật khẩu mới để hoàn tất khôi phục.": "Ingresa una contraseña nueva para completar la recuperación.",
    "Liên kết khôi phục không hợp lệ hoặc đã hết hạn.": "El enlace de recuperación no es válido o venció.",
    "Không thể cập nhật mật khẩu. Hãy thử lại.": "No se pudo actualizar la contraseña. Inténtalo de nuevo.",
    "Lưu mật khẩu mới": "Guardar contraseña nueva",
    "Mật khẩu đã được cập nhật.": "Se actualizó tu contraseña.",
    "Mã 2FA hiện tại": "Código 2FA actual",
    "Hãy nhập mã 2FA hiện tại.": "Ingresa tu código 2FA actual.",
    "Không thể xác minh trạng thái xác thực của tài khoản.": "No se pudo verificar el estado de autenticación de la cuenta.",
    "Không thể gửi email khôi phục.": "No se pudo enviar el correo de recuperación."
  };
  var ZH_CN = {
    "Khám phá nội dung": "发现内容",
    "Công trình": "结构",
    "Tài Liệu API": "API文档",
    "Tạo Map Đám Mây": "创建云地图",
    "Tạo máy chủ": "创建服务器",
    "Tải App": "获取应用程序",
    "Đăng nhập": "登录",
    "Cài đặt": "设置",
    "Nơi dành cho": "的地方",
    "mod": "模组",
    "gói tài nguyên": "资源包",
    "gói dữ liệu": "数据包",
    "shader": "光影",
    "modpack": "模组包",
    "plugin": "插件",
    "máy chủ": "服务器",
    "Khám phá, chơi và chia sẻ nội dung MiniWorld trên nền tảng được xây dựng cho cộng đồng.": "在为社区构建的平台上发现、播放和分享迷你世界内容。",
    "Khám phá các tài nguyên": "探索资源",
    "Đăng ký": "报名",
    "Dự án nổi bật": "特色项目",
    "Ánh sáng 3D cho các khối phát sáng": "发光块的 3D 照明",
    "Hệ thống kho đồ theo tủ hồ sơ": "文件柜式存储系统",
    "Rừng sâu với sinh vật mới": "森林深处有新生物",
    "Shader bầu trời chân thực": "逼真的天空着色器",
    "Logo Modium": "Modium 标志",
    "HIỂN THỊ": "展示",
    "Giao diện": "外貌",
    "Ngôn ngữ": "语言",
    "Chọn chủ đề màu ưa thích của bạn.": "选择您喜欢的颜色主题。",
    "Đồng bộ với hệ thống": "与系统同步",
    "Sáng": "光",
    "Tối": "黑暗的",
    "Đồng bộ chủ đề trên các thiết bị": "跨设备同步主题",
    "Dùng chủ đề này ở mọi nơi bạn đăng nhập. Tắt để giữ chủ đề riêng trên thiết bị này.": "在您登录的任何地方都使用此主题。关闭此主题可在此设备上保留单独的主题。",
    "Đồng bộ chủ đề": "同步主题",
    "Bố cục danh sách dự án": "项目清单布局",
    "Chọn bố cục cho từng trang hiển thị danh sách dự án.": "为显示项目列表的每个页面选择布局。",
    "Trang Mods": "模组页面",
    "Trang Plugin": "插件页面",
    "Trang Gói dữ liệu": "数据包页面",
    "Trang Shader": "着色器页面",
    "Trang Gói tài nguyên": "资源包页面",
    "Trang Modpack": "模组包页面",
    "Hàng": "行数",
    "Lưới": "网格",
    "Đổi ngôn ngữ có thể khiến một số nội dung hiển thị bằng tiếng Anh nếu chưa có bản dịch.": "更改语言可能会导致某些内容（如果尚未翻译）显示为英语。",
    "Chọn ngôn ngữ ưa thích cho trang web.": "选择您喜欢的网站语言。",
    "Tìm ngôn ngữ...": "搜索语言...",
    "Tìm ngôn ngữ": "搜索语言",
    "Ngôn ngữ tiêu chuẩn": "标准语言",
    "Đăng nhập vào Modium": "登录 Modium",
    "Email hoặc tên đăng nhập": "电子邮件或用户名",
    "Email hoặc tên @": "电子邮件或@handle",
    "Mật khẩu": "密码",
    "Tiếp tục với Email": "继续使用电子邮件",
    "Chưa có tài khoản?": "没有帐户？",
    "Đã có tài khoản?": "已经有帐户？",
    "Tạo tài khoản Modium": "创建一个 Modium 帐户",
    "Tên đăng nhập": "用户名",
    "Tên hiển thị": "显示名称",
    "Tên @ (duy nhất)": "独特的@handle",
    "Tên @": "@处理",
    "Xác nhận mật khẩu": "确认密码",
    "Ít nhất 8 ký tự": "至少 8 个字符",
    "Ít nhất 12 ký tự": "至少 12 个字符",
    "Tên này có thể trùng với người khác.": "该名称可能会被其他用户共享。",
    "Ví dụ: @minh_nguyen — chỉ gồm chữ, số, dấu _ và -.": "示例：@minh_nguyen — 仅限字母、数字、_ 和 -。",
    "Chỉ gồm chữ, số, dấu _ và -": "仅字母、数字、_ 和 -",
    "Giữ cho tôi cập nhật những điều thú vị Modium đang làm qua email": "通过电子邮件让我了解 Modium 正在开发的最新动态",
    "Hoàn tất đăng ký": "完成注册",
    "Vui lòng nhập đầy đủ thông tin.": "请填写所有字段。",
    "Email/tên đăng nhập hoặc mật khẩu không đúng.": "电子邮件/用户名或密码不正确。",
    "Tên đăng nhập phải dài 3–20 ký tự, chỉ gồm chữ, số, dấu _ và -.": "用户名必须为 3-20 个字符，并且仅包含字母、数字、_ 和 -。",
    "Tên @ phải dài 3–20 ký tự, chỉ gồm chữ, số, dấu _ và -.": "@handle 必须为 3-20 个字符，并且仅包含字母、数字、_ 和 -。",
    "Tên @ đã được sử dụng.": "该@handle 已被占用。",
    "Email không hợp lệ.": "电子邮件地址无效。",
    "Mật khẩu phải có ít nhất 8 ký tự.": "密码必须至少为 8 个字符。",
    "Mật khẩu phải có 12–128 ký tự và không chứa ký tự điều khiển.": "密码必须为 12-128 个字符，且不包含控制字符。",
    "Tên hiển thị dài 1–40 ký tự và không chứa ký tự đặc biệt nguy hiểm.": "显示名称必须为 1–40 个字符，并且不包含不安全字符。",
    "Mật khẩu xác nhận không khớp.": "密码不匹配。",
    "Tên đăng nhập đã được sử dụng.": "该用户名已被占用。",
    "Email đã được sử dụng.": "该电子邮件已被使用。",
    "Trình duyệt này không hỗ trợ mã hóa mật khẩu an toàn.": "此浏览器不支持安全密码散列。",
    "Không thể lưu tài khoản. Hãy kiểm tra trình duyệt có đang chặn lưu trữ không.": "无法保存帐户。检查您的浏览器是否阻止存储。",
    "Bạn đã thử quá nhiều lần. Hãy thử lại sau 30 giây.": "尝试次数太多。请在 30 秒后重试。",
    "Đăng nhập bằng dịch vụ bên ngoài cần máy chủ nên chưa khả dụng trong bản demo này.": "使用外部服务登录需要服务器，因此在本演示中尚不可用。",
    "Khôi phục mật khẩu cần máy chủ gửi email nên chưa khả dụng trong bản demo này.": "密码恢复需要服务器发送电子邮件，因此此演示中尚不可用。",
    "Tiếp tục với passkey": "使用密钥继续",
    "Quên mật khẩu": "忘记密码",
    "Menu tài khoản": "账户菜单",
    "Đăng bài": "发布",
    "Hồ sơ": "轮廓",
    "Nâng cấp lên Modium+": "升级到 Modium+",
    "Máy chủ của tôi": "我的服务器",
    "Thông báo": "通知",
    "Báo cáo đang xử lý": "活跃报告",
    "Bộ sưu tập": "收藏",
    "Dự án": "项目",
    "Tổ chức": "组织机构",
    "Phân tích": "分析",
    "Doanh thu": "收入",
    "Chuyển tài khoản": "切换账户",
    "Đăng xuất": "登出",
    "Chào mừng trở lại,": "欢迎回来，",
    "Đến bảng điều khiển": "转到仪表板",
    "Truy cập nhanh": "快速访问",
    "Xem thông tin tài khoản của bạn": "查看您的帐户详细信息",
    "Theo dõi hoạt động của bạn": "追踪您的活动",
    "Tùy chỉnh giao diện và ngôn ngữ": "自定义外观和语言",
    "Bảng điều khiển": "仪表板",
    "Tham gia": "已加入",
    "Lượt tải": "下载",
    "Người theo dõi": "追随者",
    "Bạn chưa có dự án nào": "您还没有项目",
    "Tính năng đăng dự án chưa khả dụng trong bản demo này.": "此演示中尚不支持发布项目。",
    "Mods": "模组",
    "Gói tài nguyên": "资源包",
    "Gói dữ liệu": "数据包",
    "Shader": "着色器",
    "Modpack": "模组包",
    "Plugin": "插件",
    "Máy chủ": "服务器",
    "Loại tài nguyên": "资源类型",
    "Bộ lọc": "过滤器",
    "Tìm kiếm dự án...": "搜索项目...",
    "Tìm kiếm dự án": "搜索项目",
    "Phiên bản trò chơi": "游戏版本",
    "Tìm kiếm...": "搜索...",
    "Tìm phiên bản": "搜索版本",
    "Hiện tất cả phiên bản": "显示所有版本",
    "Bộ nạp": "装载机",
    "Hiện thêm": "显示更多",
    "Thu gọn": "显示较少",
    "Danh mục": "类别",
    "Môi trường": "环境",
    "Phía máy khách": "客户端",
    "Phía máy chủ": "服务器端",
    "Máy khách và máy chủ": "客户端和服务器",
    "Máy khách hoặc máy chủ": "客户端或服务器",
    "Giấy phép": "执照",
    "Mã nguồn mở": "开源",
    "Phụ thuộc vào": "取决于",
    "Tìm một dự án...": "搜索项目...",
    "Tìm dự án phụ thuộc": "搜索依赖项目",
    "Loại trừ nâng cao": "高级排除",
    "Ẩn các danh mục sau": "隐藏这些类别",
    "Sắp xếp theo:": "排序方式：",
    "Mức liên quan": "关联",
    "Lượt tải nhiều nhất": "下载次数最多",
    "Được theo dõi nhiều nhất": "大多数关注",
    "Cập nhật gần đây": "最近更新",
    "Hiển thị:": "看法：",
    "Đổi bố cục": "更改布局",
    "Trang trước": "上一页",
    "Trang sau": "下一页",
    "kết quả": "结果",
    "bởi": "经过",
    "Không tìm thấy dự án phù hợp": "没有找到匹配的项目",
    "Hãy thử bỏ bớt bộ lọc.": "尝试删除一些过滤器。",
    "Xóa bộ lọc": "清除过滤器",
    "Dữ liệu minh họa: các dự án trên trang này là mẫu tự tạo.": "演示数据：此页面上的项目是虚构的示例。",
    "Phiêu lưu": "冒险",
    "Bị nguyền": "被诅咒的",
    "Trang trí": "装饰",
    "Kinh tế": "经济",
    "Trang bị": "设备",
    "Thức ăn": "食物",
    "Cơ chế game": "游戏机制",
    "Thư viện": "图书馆",
    "Phép thuật": "魔法",
    "Quản lý": "管理",
    "Sinh vật": "暴民",
    "Tối ưu hóa": "优化",
    "Xã hội": "社会的",
    "Kho chứa": "贮存",
    "Công nghệ": "技术",
    "Vận chuyển": "运输",
    "Tiện ích": "公用事业",
    "Tạo thế giới": "世界一代",
    "Độ phân giải": "分辨率",
    "8x trở xuống": "8 倍或更低",
    "512x trở lên": "512x 或更高",
    "Âm thanh": "声音的",
    "Khối": "积木",
    "Chiến đấu": "战斗",
    "Phông chữ": "字体",
    "Giao diện (GUI)": "图形用户界面",
    "Vật phẩm": "项目",
    "Bản địa hóa": "语言环境",
    "Mô hình": "型号",
    "Loại trừ": "排除",
    "Chưa có tài nguyên nào": "还没有资源",
    "Hãy là người đầu tiên chia sẻ sáng tạo của bạn với cộng đồng.": "成为第一个与社区分享您的创作的人。",
    "Đăng tài nguyên": "发布资源",
    "Bạn có những thay đổi chưa được lưu": "您有未保存的更改",
    "Đặt lại": "重置",
    "Lưu": "节省",
    "Modium là": "钠是",
    "mã nguồn mở được làm bởi Vazkii": "开源，由 Vazkii 制作",
    "Giới thiệu": "关于",
    "Tin tức": "消息",
    "Nhật ký thay đổi": "变更日志",
    "Trạng thái": "地位",
    "Tuyển dụng": "职业机会",
    "Chương trình phần thưởng": "奖励计划",
    "Sản phẩm": "产品",
    "Ứng dụng Modium": "中度应用程序",
    "Tài nguyên": "资源",
    "Trung tâm trợ giúp": "帮助中心",
    "Dịch thuật": "翻译",
    "Báo cáo sự cố": "报告问题",
    "Tài liệu API": "API文档",
    "Pháp lý": "合法的",
    "Quy tắc về nội dung": "内容规则",
    "Điều khoản sử dụng": "使用条款",
    "Chính sách quyền riêng tư": "隐私政策",
    "Thông báo bảo mật": "安全须知",
    "Chính sách bản quyền và DMCA": "版权和 DMCA 政策",
    "ĐÂY KHÔNG PHẢI WEB CHÍNH THỨ CỦA NHÀ PHÁT TRIỂN MINI WAN, ĐÂY LÀ MỘT DỰ ÁN TÔI MUỐN CÔNG KHAI MỘT SỐ THỨ VỚI MỌI NGƯỜI VÀ CHẮC CHẮN LÀ NÓ LEGIT": "这不是 MINI WAN 开发者的官方网站。这是一个我想与所有人公开分享的项目，而且它绝对是合法的",
    "Ai cũng thấy và tìm được dự án.": "每个人都可以看到并找到该项目。",
    "Bạn chưa có dự án nào!": "您还没有任何项目！",
    "Bạn chưa đăng nhập.": "您还没有登录。",
    "Bạn đã vượt giới hạn tổng 100 MB tệp trong bản demo.": "您已超出演示中 100 MB 的总文件限制。",
    "Chi tiết": "详细信息",
    "Chưa chọn tệp": "未选择文件",
    "Chưa có gì để hiển thị ở đây.": "这里还没有什么可显示的。",
    "Chưa có phiên bản nào được đăng.": "尚未发布任何版本。",
    "Chưa có thay đổi nào.": "目前还没有任何变化。",
    "Chưa có ảnh nào trong thư viện.": "图库中还没有照片。",
    "Chế độ hiển thị": "显示方式",
    "Chỉ bạn và cộng tác viên xem được.": "只有您和您的合作者可以看到它。",
    "Chỉ người có liên kết mới xem được.": "只有知道链接的人才能看到它。",
    "Chủ sở hữu": "所有者",
    "Chủ đề (chọn nhiều)": "主题（多选）",
    "Có lỗi xảy ra, trình duyệt có thể không hỗ trợ mã hóa an toàn.": "发生错误，浏览器可能不支持安全加密。",
    "Công khai": "民众",
    "Cập nhật": "更新",
    "Cộng tác viên": "合作者",
    "Cộng tác viên (không bắt buộc)": "合作者（非必需）",
    "Dùng URL": "使用网址",
    "Dữ liệu thay đổi không hợp lệ.": "更改后的数据无效。",
    "Dự án không tồn tại hoặc bạn không có quyền truy cập.": "该项目不存在或您无权访问。",
    "Dự án này chưa có tệp hoặc đường dẫn tải xuống hợp lệ.": "该项目还没有有效的文件或下载链接。",
    "Email mới": "新电子邮件",
    "Español (España)": "西班牙语（España）",
    "Español (Latinoamérica)": "西班牙语（拉丁美洲）",
    "Français": "法国人",
    "Giới thiệu chỉ được dài tối đa 160 ký tự.": "简介最多只能有 160 个字符。",
    "Hành động này không thể hoàn tác.": "此操作无法撤消。",
    "Hãy chia sẻ mod, modpack hay gói tài nguyên đầu tiên của bạn.": "请分享您的第一个模组、模组包或资源包。",
    "Hãy chọn chế độ hiển thị.": "请选择显示模式。",
    "Hãy chọn loại dự án.": "请选择项目类型。",
    "Hãy chọn tải tệp lên hoặc nhập URL tải xuống.": "选择上传文件或输入下载 URL。",
    "Hãy chọn tệp cần tải lên.": "选择要上传的文件。",
    "Hãy chọn độ phân giải của gói tài nguyên.": "请选择资源包分辨率。",
    "Hãy nhập URL HTTP/HTTPS hợp lệ (không dùng javascript:, data: hoặc thông tin đăng nhập trong URL).": "请输入有效的 HTTP/HTTPS URL（请勿在 URL 中使用 javascript:、data: 或登录信息）。",
    "Hãy nhập mô tả ngắn hợp lệ (tối đa 200 ký tự).": "请输入有效的简短描述（最多 200 个字符）。",
    "Hãy nhập đúng tên @ để xác nhận.": "请输入正确的@名称进行确认。",
    "Hôm nay": "今天",
    "hôm nay": "今天",
    "Kho tệp đang được mở ở thẻ khác. Hãy tải lại trang rồi thử lại.": "文件存储在另一个选项卡中打开。请重新加载页面并重试。",
    "Không công khai": "不公开",
    "Không dọn được tệp.": "无法清理文件。",
    "Không mở được kho tệp.": "无法打开文件存储。",
    "Không thể cập nhật bảo mật tài khoản.": "无法更新帐户安全性。",
    "Không thể lưu phiên đăng nhập. Hãy kiểm tra trình duyệt có đang chặn lưu trữ không.": "无法保存登录会话。检查您的浏览器是否阻止存储。",
    "Không thể lưu thay đổi.": "无法保存更改。",
    "Không thể lưu tệp trong trình duyệt.": "该文件无法保存在浏览器中。",
    "Không thể lưu tệp. Hãy kiểm tra dung lượng trống của trình duyệt.": "无法保存文件。检查浏览器的可用空间。",
    "Không thể tạo dự án. Hãy thử lại.": "无法创建项目。请再试一次。",
    "Không thể tạo khóa 2FA trên trình duyệt này.": "无法在此浏览器上生成 2FA 密钥。",
    "Không thể tải tệp. Hãy thử lại.": "无法加载文件。请再试一次。",
    "Không thể xóa dữ liệu dự án của tài khoản.": "该帐户的项目数据无法删除。",
    "Không thể xóa tài khoản.": "帐户无法删除。",
    "Không thể đọc tệp trong trình duyệt. Hãy thử lại.": "无法在浏览器中读取该文件。请再试一次。",
    "Không tìm thấy tệp trên thiết bị này. Trong bản demo, tệp upload chưa được đồng bộ lên máy chủ.": "在此设备上找不到文件。演示中，上传的文件尚未同步到服务器。",
    "Không xóa được tệp tạm.": "无法删除临时文件。",
    "Không đọc được tệp.": "无法读取文件。",
    "Loại dự án": "项目类型",
    "Magyar (Magyarország)": "马扎尔语 (Magyarorszag)",
    "Mã 6 số hiện trong ứng dụng": "6 位数字代码出现在应用程序中",
    "Mã không đúng. Hãy thử mã mới trong ứng dụng.": "代码不正确。在应用程序中尝试新代码。",
    "Mã xác thực 2 bước": "两步验证码",
    "Mã xác thực không đúng.": "验证码不正确。",
    "Mô tả": "描述",
    "Mô tả ngắn": "简短描述",
    "Mật khẩu hiện tại": "当前密码",
    "Mật khẩu hiện tại không đúng.": "当前密码不正确。",
    "Mật khẩu mới (≥ 12 ký tự)": "新密码（≥12个字符）",
    "Mật khẩu mới phải có 12–128 ký tự và không chứa ký tự điều khiển.": "新密码的长度必须为 12-128 个字符，并且不包含控制字符。",
    "Người dùng Modium.": "中等用户。",
    "Người dùng này chưa có dự án nào!": "该用户还没有任何项目！",
    "Người sáng tạo": "创作者",
    "Nhập mã xác thực 2 bước từ ứng dụng của bạn.": "输入应用程序中的两步验证码。",
    "Phiên bản": "版本",
    "Riêng tư": "私人的",
    "Thiết lập": "建立",
    "Thông tin": "信息",
    "Nền tảng": "平台",
    "Loại": "类型",
    "Hiển thị": "可见性",
    "Tải xuống": "下载",
    "Thẻ": "卡片",
    "Tiếng Việt": "越南语",
    "Trình duyệt không hỗ trợ lưu tệp an toàn (IndexedDB).": "浏览器不支持安全文件保存（IndexedDB）。",
    "Trình duyệt không hỗ trợ tạo mã tệp an toàn.": "浏览器不支持安全文件加密。",
    "Tài khoản và bảo mật": "账户与安全",
    "Tài khoản đã đạt giới hạn 100 dự án trong bản demo.": "该帐户已达到演示中 100 个项目的限制。",
    "Tên @ không hợp lệ.": "@名称无效。",
    "Tên @ không thể đổi sau khi tạo tài khoản để bảo vệ liên kết dự án.": "@name 在创建帐户后无法更改，以保护项目链接。",
    "Tên dự án": "项目名称",
    "Tên dự án phải dài 3–40 ký tự hợp lệ.": "项目名称的长度必须为 3-40 个有效字符。",
    "Tên tệp không hợp lệ.": "文件名无效。",
    "Tạo dự án": "创建项目",
    "Tải tệp lên": "上传文件",
    "Tải về bản sao dữ liệu tài khoản của bạn (JSON).": "下载您的帐户数据 (JSON) 的副本。",
    "Tất cả": "全部",
    "Tắt 2FA": "关闭 2FA",
    "Tệp không phải ảnh hợp lệ.": "该文件不是有效的图像。",
    "Tệp phải có dung lượng từ 1 byte đến 25 MB.": "文件大小必须介于 1 字节到 25 MB 之间。",
    "Tệp phải từ 1 byte đến 25 MB.": "文件大小必须介于 1 字节到 25 MB 之间。",
    "Tệp tải xuống": "下载文件",
    "Tệp vượt quá giới hạn dung lượng.": "文件超出容量限制。",
    "URL chỉ gồm chữ thường, số, dấu - (3–40 ký tự).": "URL 仅包含小写字母、数字和 - 符号（3–40 个字符）。",
    "URL này đã được dùng, hãy đổi tên khác.": "该网址已被使用，请更改名称。",
    "Xuất": "出口",
    "Xuất dữ liệu": "导出数据",
    "Xác nhận mật khẩu mới": "确认新密码",
    "Xác thực hai bước (2FA)": "两步身份验证 (2FA)",
    "Xóa": "擦除",
    "Xóa tài khoản": "删除帐户",
    "lượt tải": "下载",
    "ngày trước": "几天前",
    "người theo dõi": "追随者",
    "năm trước": "去年",
    "tháng trước": "上个月",
    "Đang chuẩn bị tải xuống…": "正在准备下载...",
    "Đang tạo…": "创造……",
    "Đã bật xác thực hai bước.": "启用两步验证。",
    "Đã bắt đầu tải xuống.": "下载已开始。",
    "Đã lưu thay đổi.": "更改已保存。",
    "Đã lưu.": "已保存。",
    "Đã tắt xác thực hai bước.": "两步验证已禁用。",
    "Đã đổi email.": "电子邮件已更改。",
    "Đã đổi mật khẩu.": "密码已更改。",
    "Đăng": "发布",
    "Đổi email": "更改电子邮件",
    "Đổi mật khẩu": "更改密码",
    "Đổi mật khẩu đăng nhập của bạn.": "更改您的登录密码。",
    "Độ phân giải gói tài nguyên": "资源包分辨率",
    "Ảnh đại diện không hợp lệ.": "个人资料图片无效。",
    "Đang kết nối đến Modium…": "正在连接 Modium…",
    "Không thể kết nối đến dịch vụ Modium.": "无法连接到 Modium 服务。",
    "Hãy kiểm tra cấu hình Supabase và thử lại.": "请检查 Supabase 配置并重试。",
    "Thử lại": "重试",
    "Nếu email tồn tại, liên kết đặt lại mật khẩu sẽ được gửi đến hộp thư.": "如果该邮箱存在，密码重置链接将发送至其收件箱。",
    "Kiểm tra email để xác nhận tài khoản trước khi đăng nhập.": "请先检查邮箱并确认账户，然后再登录。",
    "Không thể lưu thay đổi. Hãy thử lại.": "无法保存更改，请重试。",
    "Không thể tạo khóa xác thực hai bước.": "无法创建双重身份验证密钥。",
    "Tệp tải lên tối đa 25 MB và được lưu trong kho riêng của Modium.": "上传文件大小上限为 25 MB，并存储在 Modium 的私有存储中。",
    "Hãy xác minh mật khẩu và mã 2FA hiện tại.": "请验证当前密码和 2FA 验证码。",
    "Không thể tải file lên máy chủ. Kiểm tra quota/dung lượng rồi thử lại.": "无法上传文件。请检查存储配额后重试。",
    "Tài khoản đã đạt giới hạn 100 dự án.": "此账户已达到 100 个项目的上限。",
    "Nhập mã từ ứng dụng xác thực, rồi đăng nhập lại.": "请输入身份验证器应用中的验证码，然后重新登录。",
    "Đặt lại mật khẩu": "重置密码",
    "Nhập mật khẩu mới để hoàn tất khôi phục.": "请输入新密码以完成恢复。",
    "Liên kết khôi phục không hợp lệ hoặc đã hết hạn.": "恢复链接无效或已过期。",
    "Không thể cập nhật mật khẩu. Hãy thử lại.": "无法更新密码，请重试。",
    "Lưu mật khẩu mới": "保存新密码",
    "Mật khẩu đã được cập nhật.": "密码已更新。",
    "Mã 2FA hiện tại": "当前 2FA 验证码",
    "Hãy nhập mã 2FA hiện tại.": "请输入当前的 2FA 验证码。",
    "Không thể xác minh trạng thái xác thực của tài khoản.": "无法验证账户的身份验证状态。",
    "Không thể gửi email khôi phục.": "无法发送恢复邮件。"
  };
  var JA = {
    "Khám phá nội dung": "コンテンツを発見する",
    "Công trình": "構造物",
    "Tài Liệu API": "APIドキュメント",
    "Tạo Map Đám Mây": "クラウドマップの作成",
    "Tạo máy chủ": "サーバーを作成する",
    "Tải App": "アプリを入手",
    "Đăng nhập": "ログイン",
    "Cài đặt": "設定",
    "Nơi dành cho": "の場所",
    "mod": "Mod",
    "gói tài nguyên": "リソースパック",
    "gói dữ liệu": "データパック",
    "shader": "シェーダー",
    "modpack": "MODパック",
    "plugin": "プラグイン",
    "máy chủ": "サーバー",
    "Khám phá, chơi và chia sẻ nội dung MiniWorld trên nền tảng được xây dựng cho cộng đồng.": "コミュニティ向けに構築されたプラットフォームで MiniWorld コンテンツを発見、再生、共有します。",
    "Khám phá các tài nguyên": "リソースを探索する",
    "Đăng ký": "サインアップ",
    "Dự án nổi bật": "注目のプロジェクト",
    "Ánh sáng 3D cho các khối phát sáng": "光るブロックの 3D ライティング",
    "Hệ thống kho đồ theo tủ hồ sơ": "ファイリングキャビネットスタイルのストレージシステム",
    "Rừng sâu với sinh vật mới": "新しい生き物が生息する深い森",
    "Shader bầu trời chân thực": "リアルな空シェーダー",
    "Logo Modium": "Modium のロゴ",
    "HIỂN THỊ": "画面",
    "Giao diện": "外観",
    "Ngôn ngữ": "言語",
    "Chọn chủ đề màu ưa thích của bạn.": "好みのカラーテーマを選択してください。",
    "Đồng bộ với hệ thống": "システムと同期する",
    "Sáng": "ライト",
    "Tối": "暗い",
    "Đồng bộ chủ đề trên các thiết bị": "デバイス間でテーマを同期する",
    "Dùng chủ đề này ở mọi nơi bạn đăng nhập. Tắt để giữ chủ đề riêng trên thiết bị này.": "サインインしているすべての場所でこのテーマを使用します。このデバイス上で別のテーマを保持するには、オフにします。",
    "Đồng bộ chủ đề": "同期テーマ",
    "Bố cục danh sách dự án": "プロジェクトリストのレイアウト",
    "Chọn bố cục cho từng trang hiển thị danh sách dự án.": "プロジェクト リストを表示する各ページのレイアウトを選択します。",
    "Trang Mods": "改造ページ",
    "Trang Plugin": "プラグインページ",
    "Trang Gói dữ liệu": "データパックのページ",
    "Trang Shader": "シェーダーページ",
    "Trang Gói tài nguyên": "リソース パックのページ",
    "Trang Modpack": "Modpack ページ",
    "Hàng": "行",
    "Lưới": "グリッド",
    "Đổi ngôn ngữ có thể khiến một số nội dung hiển thị bằng tiếng Anh nếu chưa có bản dịch.": "言語を変更すると、一部のコンテンツがまだ翻訳されていない場合、英語で表示されることがあります。",
    "Chọn ngôn ngữ ưa thích cho trang web.": "Web サイトで使用する言語を選択します。",
    "Tìm ngôn ngữ...": "言語を検索...",
    "Tìm ngôn ngữ": "検索言語",
    "Ngôn ngữ tiêu chuẩn": "標準言語",
    "Đăng nhập vào Modium": "Modiumにサインインする",
    "Email hoặc tên đăng nhập": "メールアドレスまたはユーザー名",
    "Email hoặc tên @": "メールアドレスまたは@ハンドル",
    "Mật khẩu": "パスワード",
    "Tiếp tục với Email": "メールで続行",
    "Chưa có tài khoản?": "アカウントをお持ちでない場合は、",
    "Đã có tài khoản?": "すでにアカウントをお持ちですか?",
    "Tạo tài khoản Modium": "Modiumアカウントを作成する",
    "Tên đăng nhập": "ユーザー名",
    "Tên hiển thị": "表示名",
    "Tên @ (duy nhất)": "ユニークな@ハンドル",
    "Tên @": "@ハンドル",
    "Xác nhận mật khẩu": "パスワードを認証する",
    "Ít nhất 8 ký tự": "少なくとも 8 文字",
    "Ít nhất 12 ký tự": "少なくとも 12 文字",
    "Tên này có thể trùng với người khác.": "この名前は他のユーザーと共有される可能性があります。",
    "Ví dụ: @minh_nguyen — chỉ gồm chữ, số, dấu _ và -.": "例: @minh_nguyen — 文字、数字、_ および - のみ。",
    "Chỉ gồm chữ, số, dấu _ và -": "文字、数字、_ および - のみ",
    "Giữ cho tôi cập nhật những điều thú vị Modium đang làm qua email": "Modium が取り組んでいることの最新情報を電子メールで知らせてください",
    "Hoàn tất đăng ký": "サインアップを完了する",
    "Vui lòng nhập đầy đủ thông tin.": "すべてのフィールドに入力してください。",
    "Email/tên đăng nhập hoặc mật khẩu không đúng.": "メールアドレス/ユーザー名またはパスワードが間違っています。",
    "Tên đăng nhập phải dài 3–20 ký tự, chỉ gồm chữ, số, dấu _ và -.": "ユーザー名は 3 ～ 20 文字で、文字、数字、_、- のみを含む必要があります。",
    "Tên @ phải dài 3–20 ký tự, chỉ gồm chữ, số, dấu _ và -.": "@handle は 3 ～ 20 文字で、文字、数字、_、- のみを含む必要があります。",
    "Tên @ đã được sử dụng.": "その @handle はすでに取得されています。",
    "Email không hợp lệ.": "メールアドレスが無効です。",
    "Mật khẩu phải có ít nhất 8 ký tự.": "パスワードは 8 文字以上である必要があります。",
    "Mật khẩu phải có 12–128 ký tự và không chứa ký tự điều khiển.": "パスワードは 12 ～ 128 文字にする必要があり、制御文字を含めることはできません。",
    "Tên hiển thị dài 1–40 ký tự và không chứa ký tự đặc biệt nguy hiểm.": "表示名は 1 ～ 40 文字にする必要があり、安全でない文字を含めることはできません。",
    "Mật khẩu xác nhận không khớp.": "パスワードが一致しません。",
    "Tên đăng nhập đã được sử dụng.": "そのユーザー名はすでに使用されています。",
    "Email đã được sử dụng.": "そのメールはすでに使用されています。",
    "Trình duyệt này không hỗ trợ mã hóa mật khẩu an toàn.": "このブラウザは安全なパスワード ハッシュをサポートしていません。",
    "Không thể lưu tài khoản. Hãy kiểm tra trình duyệt có đang chặn lưu trữ không.": "アカウントを保存できませんでした。ブラウザがストレージをブロックしていないか確認してください。",
    "Bạn đã thử quá nhiều lần. Hãy thử lại sau 30 giây.": "試行回数が多すぎます。 30 秒後にもう一度お試しください。",
    "Đăng nhập bằng dịch vụ bên ngoài cần máy chủ nên chưa khả dụng trong bản demo này.": "外部サービスを使用したサインインにはサーバーが必要なため、このデモではまだ使用できません。",
    "Khôi phục mật khẩu cần máy chủ gửi email nên chưa khả dụng trong bản demo này.": "パスワード回復には電子メールを送信するサーバーが必要なため、このデモではまだ利用できません。",
    "Tiếp tục với passkey": "パスキーを使用して続行する",
    "Quên mật khẩu": "パスワードをお忘れですか",
    "Menu tài khoản": "アカウントメニュー",
    "Đăng bài": "公開",
    "Hồ sơ": "プロフィール",
    "Nâng cấp lên Modium+": "Modium+ にアップグレードする",
    "Máy chủ của tôi": "私のサーバー",
    "Thông báo": "通知",
    "Báo cáo đang xử lý": "アクティブなレポート",
    "Bộ sưu tập": "コレクション",
    "Dự án": "プロジェクト",
    "Tổ chức": "組織",
    "Phân tích": "分析",
    "Doanh thu": "収益",
    "Chuyển tài khoản": "アカウントを切り替える",
    "Đăng xuất": "サインアウト",
    "Chào mừng trở lại,": "おかえり、",
    "Đến bảng điều khiển": "ダッシュボードに移動",
    "Truy cập nhanh": "クイックアクセス",
    "Xem thông tin tài khoản của bạn": "アカウントの詳細を表示する",
    "Theo dõi hoạt động của bạn": "アクティビティを追跡する",
    "Tùy chỉnh giao diện và ngôn ngữ": "外観と言語をカスタマイズする",
    "Bảng điều khiển": "ダッシュボード",
    "Tham gia": "参加しました",
    "Lượt tải": "ダウンロード",
    "Người theo dõi": "フォロワー",
    "Bạn chưa có dự án nào": "まだプロジェクトがありません",
    "Tính năng đăng dự án chưa khả dụng trong bản demo này.": "このデモではプロジェクトの公開はまだ利用できません。",
    "Mods": "改造",
    "Gói tài nguyên": "リソースパック",
    "Gói dữ liệu": "データパック",
    "Shader": "シェーダ",
    "Modpack": "モッドパック",
    "Plugin": "プラグイン",
    "Máy chủ": "サーバー",
    "Loại tài nguyên": "リソースの種類",
    "Bộ lọc": "フィルター",
    "Tìm kiếm dự án...": "プロジェクトを検索...",
    "Tìm kiếm dự án": "プロジェクトを検索する",
    "Phiên bản trò chơi": "ゲームバージョン",
    "Tìm kiếm...": "検索...",
    "Tìm phiên bản": "バージョンの検索",
    "Hiện tất cả phiên bản": "すべてのバージョンを表示",
    "Bộ nạp": "ローダ",
    "Hiện thêm": "もっと見る",
    "Thu gọn": "表示を少なくする",
    "Danh mục": "カテゴリ",
    "Môi trường": "環境",
    "Phía máy khách": "クライアント側",
    "Phía máy chủ": "サーバー側",
    "Máy khách và máy chủ": "クライアントとサーバー",
    "Máy khách hoặc máy chủ": "クライアントまたはサーバー",
    "Giấy phép": "ライセンス",
    "Mã nguồn mở": "オープンソース",
    "Phụ thuộc vào": "に応じて",
    "Tìm một dự án...": "プロジェクトを検索...",
    "Tìm dự án phụ thuộc": "依存関係プロジェクトの検索",
    "Loại trừ nâng cao": "高度な除外",
    "Ẩn các danh mục sau": "これらのカテゴリを非表示にする",
    "Sắp xếp theo:": "並べ替え：",
    "Mức liên quan": "関連性",
    "Lượt tải nhiều nhất": "ほとんどのダウンロード",
    "Được theo dõi nhiều nhất": "最もフォローされている",
    "Cập nhật gần đây": "最近更新された",
    "Hiển thị:": "ビュー：",
    "Đổi bố cục": "レイアウトの変更",
    "Trang trước": "前のページへ",
    "Trang sau": "次のページ",
    "kết quả": "結果",
    "bởi": "による",
    "Không tìm thấy dự án phù hợp": "一致するプロジェクトが見つかりませんでした",
    "Hãy thử bỏ bớt bộ lọc.": "いくつかのフィルターを削除してみてください。",
    "Xóa bộ lọc": "フィルターをクリアする",
    "Dữ liệu minh họa: các dự án trên trang này là mẫu tự tạo.": "デモ データ: このページのプロジェクトは作成されたサンプルです。",
    "Phiêu lưu": "アドベンチャー",
    "Bị nguyền": "呪われた",
    "Trang trí": "装飾",
    "Kinh tế": "経済",
    "Trang bị": "装置",
    "Thức ăn": "食べ物",
    "Cơ chế game": "ゲームの仕組み",
    "Thư viện": "図書館",
    "Phép thuật": "魔法",
    "Quản lý": "管理",
    "Sinh vật": "モブ",
    "Tối ưu hóa": "最適化",
    "Xã hội": "社交",
    "Kho chứa": "ストレージ",
    "Công nghệ": "テクノロジー",
    "Vận chuyển": "交通機関",
    "Tiện ích": "ユーティリティ",
    "Tạo thế giới": "世界世代",
    "Độ phân giải": "解像度",
    "8x trở xuống": "8倍以下",
    "512x trở lên": "512x以上",
    "Âm thanh": "オーディオ",
    "Khối": "ブロック",
    "Chiến đấu": "戦闘",
    "Phông chữ": "フォント",
    "Giao diện (GUI)": "GUI",
    "Vật phẩm": "アイテム",
    "Bản địa hóa": "ロケール",
    "Mô hình": "モデル",
    "Loại trừ": "除外する",
    "Chưa có tài nguyên nào": "まだリソースがありません",
    "Hãy là người đầu tiên chia sẻ sáng tạo của bạn với cộng đồng.": "あなたの作品をコミュニティと最初に共有してください。",
    "Đăng tài nguyên": "リソースを公開する",
    "Bạn có những thay đổi chưa được lưu": "未保存の変更があります",
    "Đặt lại": "リセット",
    "Lưu": "保存",
    "Modium là": "モディウムは",
    "mã nguồn mở được làm bởi Vazkii": "オープンソース、Vazkii 製",
    "Giới thiệu": "について",
    "Tin tức": "ニュース",
    "Nhật ký thay đổi": "変更履歴",
    "Trạng thái": "状態",
    "Tuyển dụng": "キャリア",
    "Chương trình phần thưởng": "特典プログラム",
    "Sản phẩm": "製品",
    "Ứng dụng Modium": "モディウムアプリ",
    "Tài nguyên": "リソース",
    "Trung tâm trợ giúp": "ヘルプセンター",
    "Dịch thuật": "翻訳",
    "Báo cáo sự cố": "問題を報告する",
    "Tài liệu API": "APIドキュメント",
    "Pháp lý": "法律上の",
    "Quy tắc về nội dung": "コンテンツルール",
    "Điều khoản sử dụng": "利用規約",
    "Chính sách quyền riêng tư": "プライバシーポリシー",
    "Thông báo bảo mật": "セキュリティに関する通知",
    "Chính sách bản quyền và DMCA": "著作権とDMCAポリシー",
    "ĐÂY KHÔNG PHẢI WEB CHÍNH THỨ CỦA NHÀ PHÁT TRIỂN MINI WAN, ĐÂY LÀ MỘT DỰ ÁN TÔI MUỐN CÔNG KHAI MỘT SỐ THỨ VỚI MỌI NGƯỜI VÀ CHẮC CHẮN LÀ NÓ LEGIT": "これは MINI WAN 開発者の公式 Web サイトではありません。これは私が皆さんと公に共有したいプロジェクトであり、間違いなく合法です",
    "Ai cũng thấy và tìm được dự án.": "誰もがプロジェクトを見て見つけることができます。",
    "Bạn chưa có dự án nào!": "まだプロジェクトがありません。",
    "Bạn chưa đăng nhập.": "まだログインしていません。",
    "Bạn đã vượt giới hạn tổng 100 MB tệp trong bản demo.": "デモで合計ファイル制限 100 MB を超えました。",
    "Chi tiết": "詳細",
    "Chưa chọn tệp": "ファイルが選択されていません",
    "Chưa có gì để hiển thị ở đây.": "ここにはまだ何も表示できません。",
    "Chưa có phiên bản nào được đăng.": "まだバージョンは投稿されていません。",
    "Chưa có thay đổi nào.": "まだ変更はありません。",
    "Chưa có ảnh nào trong thư viện.": "ギャラリーにはまだ写真がありません。",
    "Chế độ hiển thị": "表示モード",
    "Chỉ bạn và cộng tác viên xem được.": "あなたとあなたの共同編集者だけがそれを見ることができます。",
    "Chỉ người có liên kết mới xem được.": "リンクを知っている人だけが見ることができます。",
    "Chủ sở hữu": "所有者",
    "Chủ đề (chọn nhiều)": "トピック (複数選択)",
    "Có lỗi xảy ra, trình duyệt có thể không hỗ trợ mã hóa an toàn.": "エラーが発生しました。ブラウザは安全な暗号化をサポートしていない可能性があります。",
    "Công khai": "公共",
    "Cập nhật": "更新",
    "Cộng tác viên": "協力者",
    "Cộng tác viên (không bắt buộc)": "協力者（必須ではありません）",
    "Dùng URL": "URLを使用する",
    "Dữ liệu thay đổi không hợp lệ.": "変更されたデータは無効です。",
    "Dự án không tồn tại hoặc bạn không có quyền truy cập.": "プロジェクトが存在しないか、アクセス権がありません。",
    "Dự án này chưa có tệp hoặc đường dẫn tải xuống hợp lệ.": "このプロジェクトには有効なファイルまたはダウンロード リンクがまだありません。",
    "Email mới": "新しいメール",
    "Español (España)": "スペイン語 (エスパーニャ)",
    "Español (Latinoamérica)": "スペイン語 (ラテンアメリカ)",
    "Français": "フランセ",
    "Giới thiệu chỉ được dài tối đa 160 ký tự.": "紹介文の長さは最大 160 文字までです。",
    "Hành động này không thể hoàn tác.": "この操作は元に戻すことができません。",
    "Hãy chia sẻ mod, modpack hay gói tài nguyên đầu tiên của bạn.": "最初の MOD、MODPACK、またはリソース パックを共有してください。",
    "Hãy chọn chế độ hiển thị.": "表示モードを選択してください。",
    "Hãy chọn loại dự án.": "プロジェクトの種類を選択してください。",
    "Hãy chọn tải tệp lên hoặc nhập URL tải xuống.": "ファイルをアップロードするか、ダウンロード URL を入力するかを選択します。",
    "Hãy chọn tệp cần tải lên.": "アップロードするファイルを選択します。",
    "Hãy chọn độ phân giải của gói tài nguyên.": "リソース パックの解像度を選択してください。",
    "Hãy nhập URL HTTP/HTTPS hợp lệ (không dùng javascript:, data: hoặc thông tin đăng nhập trong URL).": "有効な HTTP/HTTPS URL を入力してください (URL には javascript:、data:、またはログイン情報を使用しないでください)。",
    "Hãy nhập mô tả ngắn hợp lệ (tối đa 200 ký tự).": "有効な短い説明を入力してください (最大 200 文字)。",
    "Hãy nhập đúng tên @ để xác nhận.": "確認のため正しい@名を入力してください。",
    "Hôm nay": "今日",
    "hôm nay": "今日",
    "Kho tệp đang được mở ở thẻ khác. Hãy tải lại trang rồi thử lại.": "ファイル ストアが別のタブで開かれています。ページをリロードして、もう一度お試しください。",
    "Không công khai": "非公開",
    "Không dọn được tệp.": "ファイルをクリーンアップできません。",
    "Không mở được kho tệp.": "ファイル ストアを開けません。",
    "Không thể cập nhật bảo mật tài khoản.": "アカウントのセキュリティを更新できません。",
    "Không thể lưu phiên đăng nhập. Hãy kiểm tra trình duyệt có đang chặn lưu trữ không.": "ログインセッションを保存できません。ブラウザがストレージをブロックしていないか確認してください。",
    "Không thể lưu thay đổi.": "変更を保存できません。",
    "Không thể lưu tệp trong trình duyệt.": "ファイルをブラウザに保存できません。",
    "Không thể lưu tệp. Hãy kiểm tra dung lượng trống của trình duyệt.": "ファイルを保存できませんでした。ブラウザの空き容量を確認してください。",
    "Không thể tạo dự án. Hãy thử lại.": "プロジェクトを作成できません。もう一度試してください。",
    "Không thể tạo khóa 2FA trên trình duyệt này.": "このブラウザでは 2FA キーを生成できません。",
    "Không thể tải tệp. Hãy thử lại.": "ファイルをロードできませんでした。もう一度試してください。",
    "Không thể xóa dữ liệu dự án của tài khoản.": "アカウントのプロジェクトデータは削除できません。",
    "Không thể xóa tài khoản.": "アカウントは削除できません。",
    "Không thể đọc tệp trong trình duyệt. Hãy thử lại.": "ファイルをブラウザで読み取ることができません。もう一度試してください。",
    "Không tìm thấy tệp trên thiết bị này. Trong bản demo, tệp upload chưa được đồng bộ lên máy chủ.": "このデバイス上にファイルが見つかりません。デモでは、アップロードされたファイルはサーバーに同期されていません。",
    "Không xóa được tệp tạm.": "一時ファイルを削除できません。",
    "Không đọc được tệp.": "ファイルを読み取れません。",
    "Loại dự án": "プロジェクトの種類",
    "Magyar (Magyarország)": "マジャル語 (マジャロルザグ)",
    "Mã 6 số hiện trong ứng dụng": "6桁のコードがアプリケーションに表示されます",
    "Mã không đúng. Hãy thử mã mới trong ứng dụng.": "コードが間違っています。アプリで新しいコードを試してください。",
    "Mã xác thực 2 bước": "2段階認証コード",
    "Mã xác thực không đúng.": "認証コードが間違っています。",
    "Mô tả": "説明する",
    "Mô tả ngắn": "簡単な説明",
    "Mật khẩu hiện tại": "現在のパスワード",
    "Mật khẩu hiện tại không đúng.": "現在のパスワードが間違っています。",
    "Mật khẩu mới (≥ 12 ký tự)": "新しいパスワード (12 文字以上)",
    "Mật khẩu mới phải có 12–128 ký tự và không chứa ký tự điều khiển.": "新しいパスワードの長さは 12 ～ 128 文字にする必要があり、制御文字を含めることはできません。",
    "Người dùng Modium.": "Modiumユーザー。",
    "Người dùng này chưa có dự án nào!": "このユーザーにはまだプロジェクトがありません。",
    "Người sáng tạo": "クリエイター",
    "Nhập mã xác thực 2 bước từ ứng dụng của bạn.": "アプリから2段階認証コードを入力します。",
    "Phiên bản": "バージョン",
    "Riêng tư": "プライベート",
    "Thiết lập": "確立する",
    "Thông tin": "情報",
    "Nền tảng": "プラットフォーム",
    "Loại": "種類",
    "Hiển thị": "公開範囲",
    "Tải xuống": "ダウンロード",
    "Thẻ": "カード",
    "Tiếng Việt": "ベトナム語",
    "Trình duyệt không hỗ trợ lưu tệp an toàn (IndexedDB).": "ブラウザは安全なファイル保存 (IndexedDB) をサポートしていません。",
    "Trình duyệt không hỗ trợ tạo mã tệp an toàn.": "ブラウザは安全なファイル暗号化をサポートしていません。",
    "Tài khoản và bảo mật": "アカウントとセキュリティ",
    "Tài khoản đã đạt giới hạn 100 dự án trong bản demo.": "アカウントはデモでプロジェクトの制限である 100 に達しました。",
    "Tên @ không hợp lệ.": "@Nameが無効です。",
    "Tên @ không thể đổi sau khi tạo tài khoản để bảo vệ liên kết dự án.": "プロジェクトのリンクを保護するために、アカウント作成後に @name を変更することはできません。",
    "Tên dự án": "プロジェクト名",
    "Tên dự án phải dài 3–40 ký tự hợp lệ.": "プロジェクト名は、有効な文字数が 3 ～ 40 文字である必要があります。",
    "Tên tệp không hợp lệ.": "ファイル名が無効です。",
    "Tạo dự án": "プロジェクトの作成",
    "Tải tệp lên": "ファイルをアップロードする",
    "Tải về bản sao dữ liệu tài khoản của bạn (JSON).": "アカウント データ (JSON) のコピーをダウンロードします。",
    "Tất cả": "全て",
    "Tắt 2FA": "2FA をオフにする",
    "Tệp không phải ảnh hợp lệ.": "ファイルは有効な画像ではありません。",
    "Tệp phải có dung lượng từ 1 byte đến 25 MB.": "ファイルは 1 バイトから 25 MB までである必要があります。",
    "Tệp phải từ 1 byte đến 25 MB.": "ファイルは 1 バイトから 25 MB までである必要があります。",
    "Tệp tải xuống": "ファイルをダウンロードする",
    "Tệp vượt quá giới hạn dung lượng.": "ファイルが容量制限を超えています。",
    "URL chỉ gồm chữ thường, số, dấu - (3–40 ký tự).": "URL には、小文字、数字、および - 記号 (3 ～ 40 文字) のみが含まれます。",
    "URL này đã được dùng, hãy đổi tên khác.": "この URL は既に使用されています。名前を変更してください。",
    "Xuất": "輸出",
    "Xuất dữ liệu": "データのエクスポート",
    "Xác nhận mật khẩu mới": "新しいパスワードを確認します",
    "Xác thực hai bước (2FA)": "二段階認証（2FA）",
    "Xóa": "消去",
    "Xóa tài khoản": "アカウントを削除する",
    "lượt tải": "ダウンロード",
    "ngày trước": "数日前",
    "người theo dõi": "フォロワー",
    "năm trước": "去年",
    "tháng trước": "先月",
    "Đang chuẩn bị tải xuống…": "ダウンロードの準備をしています…",
    "Đang tạo…": "作成…",
    "Đã bật xác thực hai bước.": "二段階認証が有効になりました。",
    "Đã bắt đầu tải xuống.": "ダウンロードが開始されました。",
    "Đã lưu thay đổi.": "変更が保存されました。",
    "Đã lưu.": "保存されました。",
    "Đã tắt xác thực hai bước.": "二段階認証が無効になっています。",
    "Đã đổi email.": "メールアドレスが変わりました。",
    "Đã đổi mật khẩu.": "パスワードが変更されました。",
    "Đăng": "公開",
    "Đổi email": "メールアドレスを変更する",
    "Đổi mật khẩu": "パスワードを変更する",
    "Đổi mật khẩu đăng nhập của bạn.": "ログインパスワードを変更します。",
    "Độ phân giải gói tài nguyên": "リソースパックの解像度",
    "Ảnh đại diện không hợp lệ.": "プロフィール写真が無効です。",
    "Đang kết nối đến Modium…": "Modium に接続しています…",
    "Không thể kết nối đến dịch vụ Modium.": "Modium サービスに接続できません。",
    "Hãy kiểm tra cấu hình Supabase và thử lại.": "Supabase の設定を確認して、もう一度お試しください。",
    "Thử lại": "再試行",
    "Nếu email tồn tại, liên kết đặt lại mật khẩu sẽ được gửi đến hộp thư.": "メールアドレスが登録されている場合、パスワードリセットリンクが受信トレイに送信されます。",
    "Kiểm tra email để xác nhận tài khoản trước khi đăng nhập.": "ログイン前にメールを確認してアカウントを認証してください。",
    "Không thể lưu thay đổi. Hãy thử lại.": "変更を保存できませんでした。もう一度お試しください。",
    "Không thể tạo khóa xác thực hai bước.": "二要素認証キーを作成できませんでした。",
    "Tệp tải lên tối đa 25 MB và được lưu trong kho riêng của Modium.": "アップロードは最大 25 MB で、Modium のプライベートストレージに保存されます。",
    "Hãy xác minh mật khẩu và mã 2FA hiện tại.": "現在のパスワードと 2FA コードを確認してください。",
    "Không thể tải file lên máy chủ. Kiểm tra quota/dung lượng rồi thử lại.": "ファイルをアップロードできませんでした。ストレージ容量を確認して再試行してください。",
    "Tài khoản đã đạt giới hạn 100 dự án.": "このアカウントはプロジェクト数の上限 100 件に達しました。",
    "Nhập mã từ ứng dụng xác thực, rồi đăng nhập lại.": "認証アプリのコードを入力して、もう一度ログインしてください。",
    "Đặt lại mật khẩu": "パスワードをリセット",
    "Nhập mật khẩu mới để hoàn tất khôi phục.": "新しいパスワードを入力して、復旧を完了してください。",
    "Liên kết khôi phục không hợp lệ hoặc đã hết hạn.": "復旧リンクが無効か、有効期限が切れています。",
    "Không thể cập nhật mật khẩu. Hãy thử lại.": "パスワードを更新できませんでした。もう一度お試しください。",
    "Lưu mật khẩu mới": "新しいパスワードを保存",
    "Mật khẩu đã được cập nhật.": "パスワードを更新しました。",
    "Mã 2FA hiện tại": "現在の 2FA コード",
    "Hãy nhập mã 2FA hiện tại.": "現在の 2FA コードを入力してください。",
    "Không thể xác minh trạng thái xác thực của tài khoản.": "アカウントの認証状態を確認できませんでした。",
    "Không thể gửi email khôi phục.": "復旧メールを送信できませんでした。"
  };
  var DICT = { en: EN, 'es-419': ES_419, 'zh-CN': ZH_CN, ja: JA };
  var PARTIAL_KEYS = Object.keys(EN).filter(function (k) { return k.length >= 3; }).sort(function (a, b) { return b.length - a.length; });
  var PARTIAL_RE = new RegExp(PARTIAL_KEYS.map(function (k) { return k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }).join('|'), 'g');
  var ATTRS = ['aria-label', 'placeholder', 'alt'];
  var current = 'vi';

  function table(code) {
    if (code === 'vi') return null;
    return DICT[code] || DICT[code.split('-')[0]] || EN; /* chưa có bản dịch -> tiếng Anh */
  }

  function tr(src, tbl) {
    var k = src.trim();
    if (!k || !tbl) return src;
    var translation = tbl[k] || EN[k];
    if (translation) return src.replace(k, translation);
    return src.replace(PARTIAL_RE, function (match) { return tbl[match] || EN[match] || match; });
  }

  /* Áp dụng ngôn ngữ cho toàn bộ (hoặc một phần) trang. Có thể gọi lặp lại nhiều lần. */
  function apply(root) {
    root = root || document.body;
    var tbl = table(current);
    var w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode: function (n) {
        var p = n.parentNode && n.parentNode.nodeName;
        return p === 'SCRIPT' || p === 'STYLE' ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT;
      }
    });
    var n;
    while ((n = w.nextNode())) {
      if (n.__o === undefined) n.__o = n.nodeValue; /* nhớ bản tiếng Việt gốc */
      var v = tbl ? tr(n.__o, tbl) : n.__o;
      if (n.nodeValue !== v) n.nodeValue = v;
    }
    var els = root.querySelectorAll ? root.querySelectorAll('[aria-label],[placeholder],[alt]') : [];
    Array.prototype.forEach.call(els, function (el) {
      ATTRS.forEach(function (a) {
        if (!el.hasAttribute(a)) return;
        var key = 'data-o-' + a;
        if (!el.hasAttribute(key)) el.setAttribute(key, el.getAttribute(a)); /* nhớ bản gốc */
        var o = el.getAttribute(key);
        var nv = tbl ? tr(o, tbl) : o;
        if (el.getAttribute(a) !== nv) el.setAttribute(a, nv);
      });
    });
    document.documentElement.lang = current;
  }

  /* Đổi ngôn ngữ hiện hành rồi áp dụng ngay. */
  function set(code) {
    current = code || 'vi';
    apply(document.body);
  }

  /* Dịch một câu động (vd. thông báo lỗi) theo ngôn ngữ hiện hành. */
  function t(src) { return tr(src, table(current)); }

  window.L = { t: t, set: set, apply: apply, get: function () { return current; }, dict: DICT };
})();
